import type { DiscountingLoanPayload } from './types.ts'

/**
 * The seed payload the legacy page renders from.
 *
 * PLACEHOLDER — there is no SAP source for it yet. The original checked for a global
 * `DISCOUNTING_LOAN_PAYLOAD` that nothing ever defines and fell back to this literal, so the
 * screen has never touched a backend. When a service exists, this file is what it replaces;
 * nothing else in the feature holds record literals.
 */
export const SEED_PAYLOAD: DiscountingLoanPayload = {
  companyCodes: [
    { code: 'AE13', name: 'Olam International DMCC' },
    { code: 'AE11', name: 'Olam Global Agri Pte. Ltd' },
    { code: 'SG03', name: 'Olam Global Agri Pte. Ltd' },
  ],
  statuses: ['Contract', 'Contract Settlement'],
  records: [
    {
      companyCode: 'AE13',
      companyName: 'Olam International DMCC',
      slcStructure: 'Bilateral',
      activityCatName: 'Money Market Loan',
      transactionTypeDesc: 'Purchase',
      dealNo: '32001845',
      dttkNo: '402934',
      transactionNo: 'DTX200234',
      startDate: '11-07-2024',
      noOfDays: 120,
      discountValue: 1250000,
      currency: 'USD',
      bankName: 'ABU DHABI COMMERCIAL BANK DUBAI',
      refInterestRate: 1.1,
      spreadRate: 0.2,
      accountingTypeDesc: 'Automatic',
      productType: '10A - Working Capital Loan',
      status: 'Contract',
    },
    {
      companyCode: 'AE13',
      companyName: 'Olam International DMCC',
      slcStructure: 'Structured',
      activityCatName: 'Money Market Loan',
      transactionTypeDesc: 'Purchase',
      dealNo: '32001851',
      dttkNo: '402951',
      transactionNo: 'DTX200241',
      startDate: '14-07-2024',
      noOfDays: 150,
      discountValue: 940000,
      currency: 'USD',
      bankName: 'ABU DHABI COMMERCIAL BANK DUBAI',
      refInterestRate: 1.05,
      spreadRate: 0.2,
      accountingTypeDesc: 'Manual',
      productType: '04I - Fixed-interest bonds',
      status: 'Contract',
    },
    {
      companyCode: 'AE13',
      companyName: 'Olam International DMCC',
      slcStructure: 'Bilateral',
      activityCatName: 'Money Market Loan',
      transactionTypeDesc: 'Sale',
      dealNo: '32001812',
      dttkNo: '403002',
      transactionNo: 'DTX200271',
      startDate: '08-04-2024',
      noOfDays: 90,
      discountValue: 610000,
      currency: 'USD',
      bankName: 'THE COMMERCIAL BANK OF QATAR',
      refInterestRate: 0.98,
      spreadRate: 0.2,
      accountingTypeDesc: 'Automatic',
      productType: '10B - Term Loan',
      status: 'Contract Settlement',
    },
    {
      companyCode: 'AE11',
      companyName: 'Olam Global Agri Pte. Ltd',
      slcStructure: 'Syndicated',
      activityCatName: 'Money Market Loan',
      transactionTypeDesc: 'Purchase',
      dealNo: '32001862',
      dttkNo: '402988',
      transactionNo: 'DTX200266',
      startDate: '15-05-2024',
      noOfDays: 180,
      discountValue: 475000,
      currency: 'USD',
      bankName: 'WESTPAC BANKING CORPORATION',
      refInterestRate: 0.92,
      spreadRate: 0.2,
      accountingTypeDesc: 'Manual',
      productType: '04J - Zero bonds',
      status: 'Contract',
    },
    {
      companyCode: 'AE11',
      companyName: 'Olam Global Agri Pte. Ltd',
      slcStructure: 'Bilateral',
      activityCatName: 'Money Market Loan',
      transactionTypeDesc: 'Sale',
      dealNo: '32001870',
      dttkNo: '402979',
      transactionNo: 'DTX200260',
      startDate: '02-08-2024',
      noOfDays: 120,
      discountValue: 1385000,
      currency: 'USD',
      bankName: 'BANESCO (PANAMA) S.A.',
      refInterestRate: 1.15,
      spreadRate: 0.2,
      accountingTypeDesc: 'Automatic',
      productType: '10A - Working Capital Loan',
      status: 'Contract Settlement',
    },
    {
      companyCode: 'SG03',
      companyName: 'Olam Global Agri Pte. Ltd',
      slcStructure: 'Structured',
      activityCatName: 'Money Market Loan',
      transactionTypeDesc: 'Purchase',
      dealNo: '32001879',
      dttkNo: '403018',
      transactionNo: 'DTX200279',
      startDate: '19-08-2024',
      noOfDays: 150,
      discountValue: 825000,
      currency: 'USD',
      bankName: 'ABU DHABI COMMERCIAL BANK DUBAI',
      refInterestRate: 1.02,
      spreadRate: 0.2,
      accountingTypeDesc: 'Manual',
      productType: '10B - Term Loan',
      status: 'Contract',
    },
    {
      companyCode: 'SG03',
      companyName: 'Olam Global Agri Pte. Ltd',
      slcStructure: 'Bilateral',
      activityCatName: 'Money Market Loan',
      transactionTypeDesc: 'Purchase',
      dealNo: '32001884',
      dttkNo: '403027',
      transactionNo: 'DTX200284',
      startDate: '05-09-2024',
      noOfDays: 90,
      discountValue: 1020000,
      currency: 'USD',
      bankName: 'QATAR NATIONAL BANK (QPSC)',
      refInterestRate: 0.9,
      spreadRate: 0.2,
      accountingTypeDesc: 'Automatic',
      productType: '04I - Fixed-interest bonds',
      status: 'Contract',
    },
  ],
}
