import type { CodedOption, CompanyCode, LoanRecord, Partner } from './types.ts'

/**
 * The in-page dataset the legacy screen runs on.
 *
 * QUARANTINED PLACEHOLDER. The original defines it as DEFAULT_DATA and only replaces it
 * with a global DISCOUNTING_IRS_PAYLOAD that nothing ever sets, so this screen has never
 * touched a backend and there is no SAP entity behind it yet. When a real service exists,
 * this file is what it replaces; nothing else in the feature carries seed literals.
 */

export const OUTGOING_INT_CAT: readonly CodedOption[] = [
  { code: '01', label: 'Fixed' },
  { code: '02', label: 'Variable' },
]

export const OUTGOING_INT_FRQ: readonly string[] = [
  'Monthly',
  'Quarterly',
  'Half Yearly',
  'Upfront',
  'Rear End',
]

export const INTEREST_PAYMENT_DATE: readonly string[] = [
  'Start of Period',
  'End of Period',
  'Start of Period (DTY)',
]

export const SPECIAL_CASE: readonly string[] = ['Differential LIBOR', 'DTY Interest']

export const COMPANY_CODES: readonly CompanyCode[] = [
  { code: 'SG03', name: 'Olam Global Agri Pte. Ltd' },
  { code: 'AE13', name: 'Olam International DMCC' },
  { code: 'AE11', name: 'Olam Global Agri Pte. Ltd' },
]

export const PARTNERS: readonly Partner[] = [
  { id: 'BP1001', name: 'ABU DHABI COMMERCIAL BANK DUBAI' },
  { id: 'BP1002', name: 'THE COMMERCIAL BANK OF QATAR' },
  { id: 'BP1003', name: 'WESTPAC BANKING CORPORATION' },
  { id: 'BP1004', name: 'BANESCO (PANAMA) S.A.' },
  { id: 'BP1005', name: 'QATAR NATIONAL BANK (QPSC)' },
  { id: 'BP1006', name: 'BANCO CONTINENTAL S.A.E.C.A' },
]

export const LOAN_RECORDS: readonly LoanRecord[] = [
  {
    companyCode: 'AE13',
    entityString: 'Olam International DMCC',
    dealId: '32001845',
    discLoanTxn: 'DTX200234',
    discLoanAmount: 1250000,
    currency: 'USD',
    bankName: 'ABU DHABI COMMERCIAL BANK DUBAI',
    refInterestRate: 1.1,
    spreadRate: 0.2,
    irsId: '',
    irsCompanyName: '',
    irsTxn: '',
    partnerName: '',
    startDate: '11-07-2024',
    endDate: '08-11-2024',
    resetFrequency: 'Quarterly',
    accountingType: 'Automatic',
    specialCase: 'Differential LIBOR',
  },
  {
    companyCode: 'AE13',
    entityString: 'Olam International DMCC',
    dealId: '32001851',
    discLoanTxn: 'DTX200241',
    discLoanAmount: 940000,
    currency: 'USD',
    bankName: 'ABU DHABI COMMERCIAL BANK DUBAI',
    refInterestRate: 1.05,
    spreadRate: 0.2,
    irsId: 'IRS4501',
    irsCompanyName: 'Olam International DMCC',
    irsTxn: 'IRSTX88401',
    partnerName: 'WESTPAC BANKING CORPORATION',
    startDate: '14-07-2024',
    endDate: '11-12-2024',
    resetFrequency: 'Monthly',
    accountingType: 'Manual',
    specialCase: 'DTY Interest',
  },
  {
    companyCode: 'AE13',
    entityString: 'Olam International DMCC',
    dealId: '32001812',
    discLoanTxn: 'DTX200271',
    discLoanAmount: 610000,
    currency: 'USD',
    bankName: 'THE COMMERCIAL BANK OF QATAR',
    refInterestRate: 0.98,
    spreadRate: 0.2,
    irsId: '',
    irsCompanyName: '',
    irsTxn: '',
    partnerName: '',
    startDate: '08-04-2024',
    endDate: '07-07-2024',
    resetFrequency: 'Quarterly',
    accountingType: 'Automatic',
    specialCase: 'Differential LIBOR',
  },
  {
    companyCode: 'AE11',
    entityString: 'Olam Global Agri Pte. Ltd',
    dealId: '32001862',
    discLoanTxn: 'DTX200266',
    discLoanAmount: 475000,
    currency: 'USD',
    bankName: 'WESTPAC BANKING CORPORATION',
    refInterestRate: 0.92,
    spreadRate: 0.2,
    irsId: 'IRS4488',
    irsCompanyName: 'Olam Global Agri Pte. Ltd',
    irsTxn: 'IRSTX88377',
    partnerName: 'BANESCO (PANAMA) S.A.',
    startDate: '15-05-2024',
    endDate: '11-11-2024',
    resetFrequency: 'Half Yearly',
    accountingType: 'Manual',
    specialCase: 'DTY Interest',
  },
  {
    companyCode: 'AE11',
    entityString: 'Olam Global Agri Pte. Ltd',
    dealId: '32001870',
    discLoanTxn: 'DTX200260',
    discLoanAmount: 1385000,
    currency: 'USD',
    bankName: 'BANESCO (PANAMA) S.A.',
    refInterestRate: 1.15,
    spreadRate: 0.2,
    irsId: '',
    irsCompanyName: '',
    irsTxn: '',
    partnerName: '',
    startDate: '02-08-2024',
    endDate: '30-11-2024',
    resetFrequency: 'Quarterly',
    accountingType: 'Automatic',
    specialCase: 'Differential LIBOR',
  },
  {
    companyCode: 'SG03',
    entityString: 'Olam Global Agri Pte. Ltd',
    dealId: '32001879',
    discLoanTxn: 'DTX200279',
    discLoanAmount: 825000,
    currency: 'USD',
    bankName: 'ABU DHABI COMMERCIAL BANK DUBAI',
    refInterestRate: 1.02,
    spreadRate: 0.2,
    irsId: '',
    irsCompanyName: '',
    irsTxn: '',
    partnerName: '',
    startDate: '19-08-2024',
    endDate: '16-01-2025',
    resetFrequency: 'Monthly',
    accountingType: 'Manual',
    specialCase: 'DTY Interest',
  },
  {
    companyCode: 'SG03',
    entityString: 'Olam Global Agri Pte. Ltd',
    dealId: '32001884',
    discLoanTxn: 'DTX200284',
    discLoanAmount: 1020000,
    currency: 'USD',
    bankName: 'QATAR NATIONAL BANK (QPSC)',
    refInterestRate: 0.9,
    spreadRate: 0.2,
    irsId: 'IRS4520',
    irsCompanyName: 'Olam Global Agri Pte. Ltd',
    irsTxn: 'IRSTX88420',
    partnerName: 'QATAR NATIONAL BANK (QPSC)',
    startDate: '05-09-2024',
    endDate: '04-12-2024',
    resetFrequency: 'Quarterly',
    accountingType: 'Automatic',
    specialCase: 'Differential LIBOR',
  },
  {
    companyCode: 'AE13',
    entityString: 'Olam International DMCC',
    dealId: '12001797',
    discLoanTxn: '0002701000809',
    discLoanAmount: 23680000,
    currency: 'USD',
    bankName: 'BANCO CONTINENTAL S.A.E.C.A',
    refInterestRate: 1.0,
    spreadRate: 0.0,
    irsId: 'IRS2702',
    irsCompanyName: 'Olam International DMCC',
    irsTxn: '2702000182',
    partnerName: 'BANCO CONTINENTAL S.A.E.C.A',
    startDate: '18-06-2026',
    endDate: '13-06-2027',
    resetFrequency: '',
    accountingType: '02 Monthly',
    specialCase: '',
    exampleCashflow: [
      {
        paymentDate: '18-06-2026',
        name: 'BANCO CONTINENTAL S.A.E.C.A',
        discLoan: 23680000,
        irsIncoming: 23680000,
        irsOutgoing: -23680000,
        curr: 'USD',
        flowType: 'Notional Exchange',
        intFixDate: '18-06-2026',
        status: '-',
        pctRate: 0,
        adjStatus: 'Fixed',
      },
      {
        paymentDate: '18-07-2026',
        name: 'BANCO CONTINENTAL S.A.E.C.A',
        discLoan: -91746.78,
        irsIncoming: 124320.0,
        irsOutgoing: -39466.67,
        curr: 'USD',
        flowType: 'Interest',
        intFixDate: '16-06-2026',
        status: 'Fixed',
        pctRate: 4.6493,
        adjStatus: 'Fixed',
      },
      {
        paymentDate: '18-08-2026',
        name: 'BANCO CONTINENTAL S.A.E.C.A',
        discLoan: -122346.67,
        irsIncoming: 85642.67,
        irsOutgoing: -40782.22,
        curr: 'USD',
        flowType: 'Interest',
        intFixDate: '16-07-2026',
        status: 'Not fixed',
        pctRate: 6.0,
        adjStatus: 'Not fixed',
      },
      {
        paymentDate: '18-09-2026',
        name: 'BANCO CONTINENTAL S.A.E.C.A',
        discLoan: -65251.56,
        irsIncoming: 93799.11,
        irsOutgoing: -40782.22,
        curr: 'USD',
        flowType: 'Interest',
        intFixDate: '14-08-2026',
        status: 'Not fixed',
        pctRate: 3.2,
        adjStatus: 'Not fixed',
      },
      {
        paymentDate: '18-10-2026',
        name: 'BANCO CONTINENTAL S.A.E.C.A',
        discLoan: -104586.67,
        irsIncoming: 93581.58,
        irsOutgoing: -39466.67,
        curr: 'USD',
        flowType: 'Interest',
        intFixDate: '16-09-2026',
        status: 'Not fixed',
        pctRate: 5.3,
        adjStatus: 'Not fixed',
      },
      {
        paymentDate: '18-11-2026',
        name: 'BANCO CONTINENTAL S.A.E.C.A',
        discLoan: -120307.56,
        irsIncoming: 61173.33,
        irsOutgoing: -40782.22,
        curr: 'USD',
        flowType: 'Interest',
        intFixDate: '15-10-2026',
        status: 'Not fixed',
        pctRate: 5.9,
        adjStatus: 'Not fixed',
      },
      {
        paymentDate: '18-12-2026',
        name: 'BANCO CONTINENTAL S.A.E.C.A',
        discLoan: -96693.33,
        irsIncoming: 117808.0,
        irsOutgoing: -39466.67,
        curr: 'USD',
        flowType: 'Interest',
        intFixDate: '16-11-2026',
        status: 'Not fixed',
        pctRate: 4.9,
        adjStatus: 'Not fixed',
      },
      {
        paymentDate: '18-01-2027',
        name: 'BANCO CONTINENTAL S.A.E.C.A',
        discLoan: -136620.44,
        irsIncoming: 122346.67,
        irsOutgoing: -40782.22,
        curr: 'USD',
        flowType: 'Interest',
        intFixDate: '16-12-2026',
        status: 'Not fixed',
        pctRate: 6.7,
        adjStatus: 'Not fixed',
      },
      {
        paymentDate: '18-02-2027',
        name: 'BANCO CONTINENTAL S.A.E.C.A',
        discLoan: -122346.67,
        irsIncoming: 81564.44,
        irsOutgoing: -40782.22,
        curr: 'USD',
        flowType: 'Interest',
        intFixDate: '14-01-2027',
        status: 'Not fixed',
        pctRate: 6.0,
        adjStatus: 'Not fixed',
      },
      {
        paymentDate: '18-03-2027',
        name: 'BANCO CONTINENTAL S.A.E.C.A',
        discLoan: -92088.89,
        irsIncoming: 0,
        irsOutgoing: -36835.56,
        curr: 'USD',
        flowType: 'Interest',
        intFixDate: '16-02-2027',
        status: 'Not fixed',
        pctRate: 5.0,
        adjStatus: 'Not fixed',
      },
      {
        paymentDate: '18-04-2027',
        name: 'BANCO CONTINENTAL S.A.E.C.A',
        discLoan: -87681.78,
        irsIncoming: 0,
        irsOutgoing: -40782.22,
        curr: 'USD',
        flowType: 'Interest',
        intFixDate: '16-03-2027',
        status: 'Not fixed',
        pctRate: 4.3,
        adjStatus: 'Not fixed',
      },
      {
        paymentDate: '18-05-2027',
        name: 'BANCO CONTINENTAL S.A.E.C.A',
        discLoan: -122346.67,
        irsIncoming: 0,
        irsOutgoing: -39466.67,
        curr: 'USD',
        flowType: 'Interest',
        intFixDate: '15-04-2027',
        status: 'Not fixed',
        pctRate: 6.2,
        adjStatus: 'Not fixed',
      },
      {
        paymentDate: '18-06-2027',
        name: 'BANCO CONTINENTAL S.A.E.C.A',
        discLoan: -106033.78,
        irsIncoming: 0,
        irsOutgoing: 0,
        curr: 'USD',
        flowType: 'Interest',
        intFixDate: '14-05-2027',
        status: 'Not fixed',
        pctRate: 6.2,
        adjStatus: 'Not fixed',
      },
      {
        paymentDate: '13-06-2027',
        name: 'BANCO CONTINENTAL S.A.E.C.A',
        discLoan: -23680000,
        irsIncoming: 23680000,
        irsOutgoing: -23680000,
        curr: 'USD',
        flowType: 'Notional Exchange',
        intFixDate: '13-06-2027',
        status: '-',
        pctRate: 100.0,
        adjStatus: 'Fixed',
      },
    ],
  },
]
