import type { BankAccount, IclSettings, IclRequest } from './types.ts'

/**
 * The ICL request list, bank account list and page settings the legacy page runs on.
 *
 * QUARANTINED. The original ships this literal as DEFAULT_PAYLOAD and only replaces it with
 * a global ICL_PENDING_REQUESTS_PAYLOAD that nothing ever defines, so the screen has never
 * touched a backend. When a real service exists, this file is what it replaces; nothing
 * else in the feature reads it.
 */
export const SETTINGS: IclSettings = {
  pageSize: 12,
  defaultRequestType: 'Pending',
  nextIclGivenTransaction: 2601001038
}

export const REQUESTS: readonly IclRequest[] = [
  {
    statusCode: 'PENDING',
    statusDescription: '01 - Pending for Bank Allocation',
    requestType: 'Pending',
    companyCode: 'SG03',
    companyName: 'Olam Global Agri Pte. Ltd',
    productType: '26A',
    productDescription: '26A - Inter-Co Loan Given',
    requestorCompany: 'AE13 - Olam International DMCC',
    requestNo: '22001595',
    amount: 995024.88,
    currency: 'USD',
    requestDate: '11-07-2024',
    requestedBy: 'Karthik Ramaswamy',
    startDate: '11-07-2024',
    endDate: '07-01-2025',
    partnerBankId: 'USD1',
    iclGivenTxn: '',
    ottkNo: '102934',
    transactionNo: '2601001038'
  },
  {
    statusCode: 'PENDING',
    statusDescription: '01 - Pending for Bank Allocation',
    requestType: 'Pending',
    companyCode: 'SG03',
    companyName: 'Olam Global Agri Pte. Ltd',
    productType: '26A',
    productDescription: '26A - Inter-Co Loan Given',
    requestorCompany: 'AE13 - Olam International DMCC',
    requestNo: '22001594',
    amount: 760500,
    currency: 'USD',
    requestDate: '10-07-2024',
    requestedBy: 'Melrone Dsouza',
    startDate: '10-07-2024',
    endDate: '06-01-2025',
    partnerBankId: '',
    iclGivenTxn: '',
    ottkNo: '102931',
    transactionNo: '2601001035'
  },
  {
    statusCode: 'PENDING',
    statusDescription: '01 - Pending for Bank Allocation',
    requestType: 'Pending',
    companyCode: 'SG03',
    companyName: 'Olam Global Agri Pte. Ltd',
    productType: '26A',
    productDescription: '26A - Inter-Co Loan Given',
    requestorCompany: 'AE11 - Olam Global Agri Pte. Ltd',
    requestNo: '22001566',
    amount: 525000,
    currency: 'USD',
    requestDate: '09-07-2024',
    requestedBy: 'Mansi',
    startDate: '09-07-2024',
    endDate: '05-01-2025',
    partnerBankId: '',
    iclGivenTxn: '',
    ottkNo: '102928',
    transactionNo: '2601001032'
  },
  {
    statusCode: 'PENDING',
    statusDescription: '01 - Pending for Bank Allocation',
    requestType: 'Pending',
    companyCode: 'SG03',
    companyName: 'Olam Global Agri Pte. Ltd',
    productType: '26A',
    productDescription: '26A - Inter-Co Loan Given',
    requestorCompany: 'AE13 - Olam International DMCC',
    requestNo: '26000729',
    amount: 410250.5,
    currency: 'USD',
    requestDate: '08-07-2024',
    requestedBy: 'Karthik Ramaswamy',
    startDate: '08-07-2024',
    endDate: '04-01-2025',
    partnerBankId: '',
    iclGivenTxn: '',
    ottkNo: '102924',
    transactionNo: '2601001028'
  },
  {
    statusCode: 'PENDING',
    statusDescription: '01 - Pending for Bank Allocation',
    requestType: 'Pending',
    companyCode: 'SG03',
    companyName: 'Olam Global Agri Pte. Ltd',
    productType: '26A',
    productDescription: '26A - Inter-Co Loan Given',
    requestorCompany: 'AE13 - Olam International DMCC',
    requestNo: '26000728',
    amount: 380000,
    currency: 'USD',
    requestDate: '07-07-2024',
    requestedBy: 'Sufiyan H',
    startDate: '07-07-2024',
    endDate: '03-01-2025',
    partnerBankId: '',
    iclGivenTxn: '',
    ottkNo: '102921',
    transactionNo: '2601001025'
  },
  {
    statusCode: 'PENDING',
    statusDescription: '01 - Pending for Bank Allocation',
    requestType: 'Pending',
    companyCode: 'SG03',
    companyName: 'Olam Global Agri Pte. Ltd',
    productType: '26A',
    productDescription: '26A - Inter-Co Loan Given',
    requestorCompany: 'AE11 - Olam Global Agri Pte. Ltd',
    requestNo: '26000610',
    amount: 275800.75,
    currency: 'USD',
    requestDate: '06-07-2024',
    requestedBy: 'Nithishkumar',
    startDate: '06-07-2024',
    endDate: '02-01-2025',
    partnerBankId: '',
    iclGivenTxn: '',
    ottkNo: '102918',
    transactionNo: '2601001022'
  },
  {
    statusCode: 'PENDING',
    statusDescription: '01 - Pending for Bank Allocation',
    requestType: 'Pending',
    companyCode: 'SG03',
    companyName: 'Olam Global Agri Pte. Ltd',
    productType: '26A',
    productDescription: '26A - Inter-Co Loan Given',
    requestorCompany: 'AE13 - Olam International DMCC',
    requestNo: '22001524',
    amount: 190450,
    currency: 'USD',
    requestDate: '05-07-2024',
    requestedBy: 'Jayant S',
    startDate: '05-07-2024',
    endDate: '01-01-2025',
    partnerBankId: '',
    iclGivenTxn: '',
    ottkNo: '102915',
    transactionNo: '2601001019'
  },
  {
    statusCode: 'PENDING',
    statusDescription: '01 - Pending for Bank Allocation',
    requestType: 'Pending',
    companyCode: 'SG03',
    companyName: 'Olam Global Agri Pte. Ltd',
    productType: '26A',
    productDescription: '26A - Inter-Co Loan Given',
    requestorCompany: 'AE13 - Olam International DMCC',
    requestNo: '26000724',
    amount: 150000,
    currency: 'USD',
    requestDate: '04-07-2024',
    requestedBy: 'Anbarasan K',
    startDate: '04-07-2024',
    endDate: '31-12-2024',
    partnerBankId: '',
    iclGivenTxn: '',
    ottkNo: '102912',
    transactionNo: '2601001016'
  },
  {
    statusCode: 'APPROVED',
    statusDescription: '02 - Approved by TSF Manager',
    requestType: 'Pending',
    companyCode: 'SG03',
    companyName: 'Olam Global Agri Pte. Ltd',
    productType: '26A',
    productDescription: '26A - Inter-Co Loan Given',
    requestorCompany: 'AE13 - Olam International DMCC',
    requestNo: '26000604',
    amount: 225000,
    currency: 'USD',
    requestDate: '03-07-2024',
    requestedBy: 'Karthik Ramaswamy',
    startDate: '03-07-2024',
    endDate: '30-12-2024',
    partnerBankId: 'USD1',
    iclGivenTxn: '2601001008',
    ottkNo: '102906',
    transactionNo: '2601001008'
  },
  {
    statusCode: 'APPROVED',
    statusDescription: '02 - Approved by TSF Manager',
    requestType: 'Pending',
    companyCode: 'SG03',
    companyName: 'Olam Global Agri Pte. Ltd',
    productType: '26A',
    productDescription: '26A - Inter-Co Loan Given',
    requestorCompany: 'AE11 - Olam Global Agri Pte. Ltd',
    requestNo: '26000603',
    amount: 185500,
    currency: 'USD',
    requestDate: '02-07-2024',
    requestedBy: 'Mansi',
    startDate: '02-07-2024',
    endDate: '29-12-2024',
    partnerBankId: 'USD1',
    iclGivenTxn: '2601001005',
    ottkNo: '102903',
    transactionNo: '2601001005'
  }
]

export const BANK_ACCOUNTS: readonly BankAccount[] = [
  {
    companyCode: 'SG03',
    houseBank: 'DBS03',
    bankKey: 'DBSSSGSG',
    accountId: 'DBS00',
    currency: 'USD',
    bankAccount: '0072003358012',
    description: 'OGA DBS USD 0072-003358-01-2',
    partnerBankId: 'USD1'
  },
  {
    companyCode: 'SG03',
    houseBank: 'DBS03',
    bankKey: 'DBSSSGSG',
    accountId: 'DBS03',
    currency: 'SGD',
    bankAccount: '0720362977',
    description: 'OGA DBS SGD 072-036297-7',
    partnerBankId: 'SGD1'
  },
  {
    companyCode: 'SG03',
    houseBank: 'DBS03',
    bankKey: 'DBSSSGSG',
    accountId: 'EUR01',
    currency: 'EUR',
    bankAccount: '0720486110',
    description: 'OGA DBS EUR Operating Account',
    partnerBankId: 'EUR1'
  },
  {
    companyCode: 'SG03',
    houseBank: 'DBS03',
    bankKey: 'DBSSSGSG',
    accountId: 'GBP01',
    currency: 'GBP',
    bankAccount: '0720529841',
    description: 'OGA DBS GBP Collection Account',
    partnerBankId: 'GBP1'
  },
  {
    companyCode: 'SG03',
    houseBank: 'SCB01',
    bankKey: 'SCBLSGSG',
    accountId: 'USD01',
    currency: 'USD',
    bankAccount: '0105944491',
    description: 'OGA Standard Chartered USD Account',
    partnerBankId: 'USD2'
  },
  {
    companyCode: 'SG03',
    houseBank: 'SCB01',
    bankKey: 'SCBLSGSG',
    accountId: 'SGD01',
    currency: 'SGD',
    bankAccount: '0105944524',
    description: 'OGA Standard Chartered SGD Account',
    partnerBankId: 'SGD2'
  },
  {
    companyCode: 'SG03',
    houseBank: 'SCB01',
    bankKey: 'SCBLSGSG',
    accountId: 'EUR03',
    currency: 'EUR',
    bankAccount: '0105944578',
    description: 'OGA Standard Chartered EUR Collection Account',
    partnerBankId: 'EUR3'
  },
  {
    companyCode: 'SG03',
    houseBank: 'CITI1',
    bankKey: 'CITISGSGXXX',
    accountId: 'USD02',
    currency: 'USD',
    bankAccount: '3010228199',
    description: 'OGA Citi USD Operating Account',
    partnerBankId: 'USD3'
  },
  {
    companyCode: 'SG03',
    houseBank: 'CITI1',
    bankKey: 'CITISGSGXXX',
    accountId: 'EUR02',
    currency: 'EUR',
    bankAccount: '3010228245',
    description: 'OGA Citi EUR Collection Account',
    partnerBankId: 'EUR2'
  },
  {
    companyCode: 'SG03',
    houseBank: 'JPM01',
    bankKey: 'CHASUS33XXX',
    accountId: 'CHA00',
    currency: 'USD',
    bankAccount: '759277681',
    description: 'OGA JPMorgan Chase USD Main Account',
    partnerBankId: 'USD4'
  },
  {
    companyCode: 'SG03',
    houseBank: 'JPM01',
    bankKey: 'CHASUS33XXX',
    accountId: 'CHA01',
    currency: 'EUR',
    bankAccount: '759277749',
    description: 'OGA JPMorgan Chase EUR Collection Account',
    partnerBankId: 'EUR4'
  },
  {
    companyCode: 'SG03',
    houseBank: 'JPM01',
    bankKey: 'CHASUS33XXX',
    accountId: 'CHA02',
    currency: 'SGD',
    bankAccount: '759277802',
    description: 'OGA JPMorgan Chase SGD Operating Account',
    partnerBankId: 'SGD4'
  },
  {
    companyCode: 'SG03',
    houseBank: 'JPM01',
    bankKey: 'CHASUS33XXX',
    accountId: 'CHA03',
    currency: 'JPY',
    bankAccount: '759277845',
    description: 'OGA JPMorgan Chase JPY Settlement Account',
    partnerBankId: 'JPY4'
  },
  {
    companyCode: 'SG03',
    houseBank: 'HSBC1',
    bankKey: 'HSBCSGSG',
    accountId: 'USD05',
    currency: 'USD',
    bankAccount: '141302008822',
    description: 'OGA HSBC USD Settlement Account',
    partnerBankId: 'USD5'
  },
  {
    companyCode: 'SG03',
    houseBank: 'HSBC1',
    bankKey: 'HSBCSGSG',
    accountId: 'SGD05',
    currency: 'SGD',
    bankAccount: '141302008830',
    description: 'OGA HSBC SGD Settlement Account',
    partnerBankId: 'SGD5'
  },
  {
    companyCode: 'SG03',
    houseBank: 'BOA01',
    bankKey: 'BOFAUS3NXXX',
    accountId: 'USD06',
    currency: 'USD',
    bankAccount: '6550091842',
    description: 'OGA Bank of America USD Account',
    partnerBankId: 'USD6'
  },
  {
    companyCode: 'SG03',
    houseBank: 'ICBC1',
    bankKey: 'ICBKSGSGXXX',
    accountId: 'USD07',
    currency: 'USD',
    bankAccount: '1098876501',
    description: 'OGA ICBC Singapore USD Account',
    partnerBankId: 'USD7'
  },
  {
    companyCode: 'SG03',
    houseBank: 'MIZU1',
    bankKey: 'MIZUH0XXXX',
    accountId: 'USD08',
    currency: 'USD',
    bankAccount: '4412098750',
    description: 'OGA Mizuho USD Operating Account',
    partnerBankId: 'USD8'
  }
]
