/** One row of the Adjusted Price / Qty grid. Every cell is a string as the grid edits it. */
export type InvoiceLine = {
  invoiceTypeMain: string
  drawingAmountA: string
  tradeType: string
  profitability: string
  plannedInvAmt: string
  client: string
  dealId: string
  invTrmRefNo: string
  invoiceType: string
  preTicketRefNo: string
  proposedInvDate: string
  invoiceDate: string
  soPoDate: string
  invoiceNo: string
  invoiceCommodity: string
  gtCommodityId: string
  partialComplete: string
  fixedMatDate: string
  incoterms: string
  seller: string
  buyer: string
  mcRefPurchase: string
  mcRefSale: string
  mcReferenceNo: string
  quantity: string
  price: string
  invPriceUsd: string
  invAmountUsd: string
  differenceInvAmount: string
  finalInvAmt: string
  invoiceCurrency: string
  exchangeRate: string
  plannedExchangeRate: string
  invoiceTransferred: string
  payTerms: string
  companyCode: string
  int4: string
  businessPartner: string
  houseBank: string
  accountId: string
  bankDetailsId: string
  prepaymentDiscount: string
  netAmount: string
  profitMargin: string
  blDate: string
  drawingAmountB: string
  enteredBy: string
  enteredOn: string
  entryTime: string
  lastChangedBy: string
  changedOn: string
  timeChanged: string
  amendmentCheck: string
}

/** A deal as the legacy page's DUMMY.deals defines it. No SAP entity exists for this yet. */
export type InvoiceDeal = {
  blDate: string
  busa: string
  client: string
  commodity: string
  companyCode: string
  currency: string
  deal: string
  dttk: string
  dttk_cat: string
  dttk_rate: string
  dttk_tenor: string
  entity: string
  entryDate: string
  exchangeRate: string
  fixedMatDate: string
  gtCommodityId: string
  incoterms: string
  ottk: string
  ottk_cat: string
  ottk_rate: string
  ottk_tenor: string
  payTerms: string
  plannedExchangeRate: string
  price: number
  profitMargin: string
  quantity: number
  status: string
  structure: string
}
