import type { IclPayload } from './types.ts'

/**
 * The ICL Received request list the legacy page runs on.
 *
 * PLACEHOLDER DATA — there is no SAP source for it yet. The original declares this literal
 * inline and only uses a global ICL_RECEIVED_PAYLOAD when something else defines one, which
 * nothing ever does, so this screen has never touched a backend. When a service exists, this
 * file is what it replaces; nothing else in the feature reads it.
 */
export const ICL_PAYLOAD: IclPayload = {
  settings: {
    pageSize: 12,
    nextReceivedTransaction: 2602001942,
    nextDmsCode: 6010000539,
    dateFormat: 'DD-MM-YYYY',
  },
  columns: [
    {
      key: 'statusCode',
      label: 'Status',
      width: 62,
      type: 'status',
    },
    {
      key: 'client',
      label: 'Client',
      width: 70,
    },
    {
      key: 'iclGivenCompanyCode',
      label: 'ICL Given Co.Code',
      width: 118,
    },
    {
      key: 'iclRequestNo',
      label: 'ICL Request No',
      width: 108,
    },
    {
      key: 'requestDate',
      label: 'Request Date',
      width: 94,
      type: 'date',
    },
    {
      key: 'startDate',
      label: 'Start Date',
      width: 92,
      type: 'date',
    },
    {
      key: 'endDate',
      label: 'End Date',
      width: 92,
      type: 'date',
    },
    {
      key: 'plannedEndDate',
      label: 'Planned End Date',
      width: 116,
      type: 'date',
    },
    {
      key: 'amount',
      label: 'Amount',
      width: 116,
      type: 'amount',
    },
    {
      key: 'currency',
      label: 'Currency',
      width: 72,
    },
    {
      key: 'dealId',
      label: 'Deal ID',
      width: 86,
    },
    {
      key: 'iclReqStatus',
      label: 'ICL Req Status',
      width: 96,
    },
    {
      key: 'ottkNo',
      label: 'OTTK No',
      width: 82,
    },
    {
      key: 'slcStructure',
      label: 'SLC Structure',
      width: 96,
    },
    {
      key: 'entityId',
      label: 'Entity ID',
      width: 80,
    },
    {
      key: 'entityString',
      label: 'Entity String',
      width: 176,
    },
    {
      key: 'iclRecCompanyCode',
      label: 'ICL Rec Co.Code',
      width: 116,
    },
    {
      key: 'depositRequest',
      label: 'Deposit Request',
      width: 110,
    },
    {
      key: 'houseBank',
      label: 'House Bank',
      width: 92,
    },
    {
      key: 'accountId',
      label: 'Account ID',
      width: 88,
    },
    {
      key: 'partnerBankId',
      label: 'Partner Bank ID',
      width: 110,
    },
    {
      key: 'enteredBy',
      label: 'Entered By',
      width: 112,
    },
    {
      key: 'enteredOn',
      label: 'Entered On',
      width: 92,
      type: 'date',
    },
    {
      key: 'entryTime',
      label: 'Entry Time',
      width: 82,
    },
    {
      key: 'requestedBy',
      label: 'Requested By',
      width: 116,
    },
    {
      key: 'requestorCoCode',
      label: 'Requestor Co Code',
      width: 118,
    },
    {
      key: 'requestorCoName',
      label: 'Requestor Co Name',
      width: 182,
    },
    {
      key: 'requestorBank',
      label: 'Requestor Bank',
      width: 106,
    },
    {
      key: 'requestorBankName',
      label: 'Requestor Bank Name',
      width: 170,
    },
    {
      key: 'expectedDate',
      label: 'Expected Date',
      width: 96,
      type: 'date',
    },
    {
      key: 'lcTenor',
      label: 'LC Tenor',
      width: 82,
    },
    {
      key: 'businessArea',
      label: 'Business Area',
      width: 98,
    },
    {
      key: 'ottkClassification',
      label: 'OTTK Classification',
      width: 126,
    },
    {
      key: 'dttkNo',
      label: 'DTTK No',
      width: 84,
    },
    {
      key: 'iclRequestStatusDescription',
      label: 'ICL Request Status Description',
      width: 196,
    },
    {
      key: 'percentageRate',
      label: 'Percentage Rate',
      width: 108,
      type: 'rate',
    },
    {
      key: 'fixing',
      label: 'Fixing',
      width: 72,
    },
    {
      key: 'depositCompanyCode',
      label: 'Deposit Co.Code',
      width: 112,
    },
    {
      key: 'depositTxn',
      label: 'Deposit Txn',
      width: 94,
    },
    {
      key: 'wcdlCompanyCode',
      label: 'WCDL Co.Code',
      width: 106,
    },
    {
      key: 'iclRecTxn',
      label: 'ICL Rec Txn',
      width: 102,
    },
    {
      key: 'iclGivenTxn',
      label: 'ICL Given Txn',
      width: 104,
    },
    {
      key: 'companyName',
      label: 'Company Name',
      width: 180,
    },
    {
      key: 'activeStatus',
      label: 'Active Status',
      width: 94,
    },
    {
      key: 'productType',
      label: 'Product Type',
      width: 90,
    },
    {
      key: 'productTypeDescription',
      label: 'Product Type Description',
      width: 176,
    },
    {
      key: 'transactionType',
      label: 'Transaction Type',
      width: 106,
    },
    {
      key: 'transactionTypeDescription',
      label: 'Transaction Type Description',
      width: 188,
    },
    {
      key: 'iclReceivedBank',
      label: 'ICL Received Bank',
      width: 124,
    },
    {
      key: 'activeActivity',
      label: 'Active Activity',
      width: 104,
    },
    {
      key: 'businessPartner',
      label: 'Business Partner',
      width: 112,
    },
    {
      key: 'profitCenter',
      label: 'Profit Center',
      width: 96,
    },
    {
      key: 'profitCenterDescription',
      label: 'Profit Center Description',
      width: 174,
    },
    {
      key: 'businessAreaDescription',
      label: 'Business Area Desc',
      width: 142,
    },
    {
      key: 'portfolio',
      label: 'Portfolio',
      width: 86,
    },
    {
      key: 'accountingCategory',
      label: 'Accounting Category',
      width: 130,
    },
    {
      key: 'iclGivenPrd',
      label: 'ICL Given Prd',
      width: 100,
    },
    {
      key: 'iclGivenPrdDesc',
      label: 'ICL Given Prd Desc',
      width: 168,
    },
    {
      key: 'iclRecPrd',
      label: 'ICL Rec Prd',
      width: 96,
    },
    {
      key: 'iclRecPrdDesc',
      label: 'ICL Rec Prd Desc',
      width: 168,
    },
  ],
  rows: [
    {
      statusCode: 'PENDING',
      client: '300',
      iclGivenCompanyCode: 'SG03',
      iclRequestNo: '22001612',
      requestDate: '21-01-26',
      startDate: '21-01-26',
      endDate: '16-01-27',
      plannedEndDate: '31-01-26',
      amount: 2865.46,
      currency: 'USD',
      dealId: '12001332',
      iclReqStatus: '03',
      ottkNo: '101183',
      slcStructure: 'DSX',
      entityId: 'E021',
      entityString: 'E021 - OGA-DMCC-PAN',
      iclRecCompanyCode: '',
      depositRequest: '',
      houseBank: '',
      accountId: '',
      partnerBankId: '',
      enteredBy: 'ALOR',
      enteredOn: '21-01-26',
      entryTime: '11:400',
      requestedBy: 'Treasury User',
      requestorCoCode: 'SG03',
      requestorCoName: 'Olam Global Agri Pte. Ltd',
      requestorBank: 'DBS03',
      requestorBankName: 'DBS Bank Singapore',
      expectedDate: '31-01-26',
      lcTenor: '12M',
      businessArea: 'TSF',
      ottkClassification: 'Direct',
      dttkNo: '200001',
      iclRequestStatusDescription: '03 - Approved for ICL Received',
      percentageRate: 5.25,
      fixing: 'Fixed',
      depositCompanyCode: '',
      depositTxn: '',
      wcdlCompanyCode: '',
      iclRecTxn: '',
      iclGivenTxn: '2601000500',
      companyName: 'Olam Global Agri Pte. Ltd',
      activeStatus: 'Active',
      productType: '26A',
      productTypeDescription: 'Inter-Co Loan Given',
      transactionType: '100',
      transactionTypeDescription: 'ICL Given',
      iclReceivedBank: '',
      activeActivity: 'Create',
      businessPartner: 'BP010300',
      profitCenter: 'PC1000',
      profitCenterDescription: 'Treasury Finance',
      businessAreaDescription: 'Trade Structured Finance',
      portfolio: 'PF01',
      accountingCategory: 'AC01',
      iclGivenPrd: '26A',
      iclGivenPrdDesc: 'Inter-Co Loan Given',
      iclRecPrd: '26B',
      iclRecPrdDesc: 'Inter-Co Loan Received',
      targetReceivedCompanyCode: 'AE13',
      dms: {
        docType: 'D01',
        docTypeDesc: 'ICL Received Slip',
        docDate: '',
        filePath: '',
        fileName: '',
        dmsCode: '',
        uploaded: false,
        finalized: false,
      },
    },
    {
      statusCode: 'PENDING',
      client: '300',
      iclGivenCompanyCode: 'SG03',
      iclRequestNo: '22001613',
      requestDate: '21-01-26',
      startDate: '21-01-26',
      endDate: '16-01-27',
      plannedEndDate: '31-01-26',
      amount: 5000,
      currency: 'USD',
      dealId: '12001333',
      iclReqStatus: '03',
      ottkNo: '101182',
      slcStructure: 'DSX',
      entityId: 'E021',
      entityString: 'E021 - OGA-DMCC-PAN',
      iclRecCompanyCode: '',
      depositRequest: '',
      houseBank: '',
      accountId: '',
      partnerBankId: '',
      enteredBy: 'TREASURY01',
      enteredOn: '21-01-26',
      entryTime: '11:401',
      requestedBy: 'OIL Treasury',
      requestorCoCode: 'SG03',
      requestorCoName: 'Olam Global Agri Pte. Ltd',
      requestorBank: 'SCB01',
      requestorBankName: 'Standard Chartered Singapore',
      expectedDate: '31-01-26',
      lcTenor: '12M',
      businessArea: 'TSF',
      ottkClassification: 'Reference',
      dttkNo: '',
      iclRequestStatusDescription: '03 - Approved for ICL Received',
      percentageRate: 5.25,
      fixing: 'Float',
      depositCompanyCode: '',
      depositTxn: '',
      wcdlCompanyCode: '',
      iclRecTxn: '',
      iclGivenTxn: '2601000501',
      companyName: 'Olam Global Agri Pte. Ltd',
      activeStatus: 'Active',
      productType: '26A',
      productTypeDescription: 'Inter-Co Loan Given',
      transactionType: '100',
      transactionTypeDescription: 'ICL Given',
      iclReceivedBank: '',
      activeActivity: 'Create',
      businessPartner: 'BP010301',
      profitCenter: 'PC1000',
      profitCenterDescription: 'Treasury Finance',
      businessAreaDescription: 'Trade Structured Finance',
      portfolio: 'PF01',
      accountingCategory: 'AC01',
      iclGivenPrd: '26A',
      iclGivenPrdDesc: 'Inter-Co Loan Given',
      iclRecPrd: '26B',
      iclRecPrdDesc: 'Inter-Co Loan Received',
      targetReceivedCompanyCode: 'AE13',
      dms: {
        docType: 'D01',
        docTypeDesc: 'ICL Received Slip',
        docDate: '',
        filePath: '',
        fileName: '',
        dmsCode: '',
        uploaded: false,
        finalized: false,
      },
    },
    {
      statusCode: 'RECEIVED',
      client: '300',
      iclGivenCompanyCode: 'AE13',
      iclRequestNo: '22001486',
      requestDate: '01-12-25',
      startDate: '01-12-25',
      endDate: '26-11-27',
      plannedEndDate: '11-12-25',
      amount: 4783.99,
      currency: 'USD',
      dealId: '',
      iclReqStatus: '04',
      ottkNo: '100910',
      slcStructure: 'DSX',
      entityId: 'E021',
      entityString: 'E021 - OGA-DMCC-PAN',
      iclRecCompanyCode: 'SG03',
      depositRequest: '',
      houseBank: '',
      accountId: '',
      partnerBankId: '',
      enteredBy: 'TREASURY01',
      enteredOn: '01-12-25',
      entryTime: '11:402',
      requestedBy: 'Treasury User',
      requestorCoCode: 'AE13',
      requestorCoName: 'Olam International DMCC',
      requestorBank: 'DBS03',
      requestorBankName: 'DBS Bank Singapore',
      expectedDate: '11-12-25',
      lcTenor: '12M',
      businessArea: 'TSF',
      ottkClassification: 'Reference',
      dttkNo: '',
      iclRequestStatusDescription: '03 - Approved for ICL Received',
      percentageRate: 5.25,
      fixing: 'Fixed',
      depositCompanyCode: '',
      depositTxn: '',
      wcdlCompanyCode: '',
      iclRecTxn: '2602001941',
      iclGivenTxn: '2601000502',
      companyName: 'Olam International DMCC',
      activeStatus: 'Active',
      productType: '26A',
      productTypeDescription: 'Inter-Co Loan Given',
      transactionType: '100',
      transactionTypeDescription: 'ICL Given',
      iclReceivedBank: '',
      activeActivity: 'Create',
      businessPartner: 'BP010302',
      profitCenter: 'PC1000',
      profitCenterDescription: 'Treasury Finance',
      businessAreaDescription: 'Trade Structured Finance',
      portfolio: 'PF01',
      accountingCategory: 'AC01',
      iclGivenPrd: '26A',
      iclGivenPrdDesc: 'Inter-Co Loan Given',
      iclRecPrd: '26B',
      iclRecPrdDesc: 'Inter-Co Loan Received',
      targetReceivedCompanyCode: 'SG03',
      dms: {
        docType: 'D01',
        docTypeDesc: 'ICL Received Slip',
        docDate: '20-08-26',
        filePath: 'C:\\Users\\alor\\Documents\\SAP\\ICL_Received_22001486.pdf',
        fileName: 'ICL_Received_22001486.pdf',
        dmsCode: '6010000538',
        uploaded: true,
        finalized: true,
      },
    },
    {
      statusCode: 'PENDING',
      client: '300',
      iclGivenCompanyCode: 'SG03',
      iclRequestNo: '22001635',
      requestDate: '03-02-26',
      startDate: '03-02-26',
      endDate: '04-01-26',
      plannedEndDate: '07-02-26',
      amount: 75000,
      currency: 'USD',
      dealId: '14000539',
      iclReqStatus: '03',
      ottkNo: '400507',
      slcStructure: 'ICFSI',
      entityId: 'E103',
      entityString: 'E103 - VEND-OAL-CUST',
      iclRecCompanyCode: '',
      depositRequest: '',
      houseBank: '',
      accountId: '',
      partnerBankId: '',
      enteredBy: 'ALOR',
      enteredOn: '03-02-26',
      entryTime: '11:403',
      requestedBy: 'OIL Treasury',
      requestorCoCode: 'SG03',
      requestorCoName: 'Olam Global Agri Pte. Ltd',
      requestorBank: 'SCB01',
      requestorBankName: 'Standard Chartered Singapore',
      expectedDate: '07-02-26',
      lcTenor: '6M',
      businessArea: 'TSF',
      ottkClassification: 'Direct',
      dttkNo: '',
      iclRequestStatusDescription: '03 - Approved for ICL Received',
      percentageRate: 4.75,
      fixing: 'Float',
      depositCompanyCode: '',
      depositTxn: '',
      wcdlCompanyCode: '',
      iclRecTxn: '',
      iclGivenTxn: '2601000503',
      companyName: 'Olam Global Agri Pte. Ltd',
      activeStatus: 'Active',
      productType: '26A',
      productTypeDescription: 'Inter-Co Loan Given',
      transactionType: '100',
      transactionTypeDescription: 'ICL Given',
      iclReceivedBank: '',
      activeActivity: 'Create',
      businessPartner: 'BP010303',
      profitCenter: 'PC2000',
      profitCenterDescription: 'Vendor Financing',
      businessAreaDescription: 'Trade Structured Finance',
      portfolio: 'PF01',
      accountingCategory: 'AC01',
      iclGivenPrd: '26A',
      iclGivenPrdDesc: 'Inter-Co Loan Given',
      iclRecPrd: '26B',
      iclRecPrdDesc: 'Inter-Co Loan Received',
      targetReceivedCompanyCode: 'AE13',
      dms: {
        docType: 'D01',
        docTypeDesc: 'ICL Received Slip',
        docDate: '',
        filePath: '',
        fileName: '',
        dmsCode: '',
        uploaded: false,
        finalized: false,
      },
    },
    {
      statusCode: 'PENDING',
      client: '300',
      iclGivenCompanyCode: 'SG03',
      iclRequestNo: '22001624',
      requestDate: '28-01-26',
      startDate: '28-01-26',
      endDate: '23-01-27',
      plannedEndDate: '07-02-26',
      amount: 955153.99,
      currency: 'USD',
      dealId: '12001348',
      iclReqStatus: '03',
      ottkNo: '101205',
      slcStructure: 'DSX',
      entityId: 'E021',
      entityString: 'E021 - OGA-DMCC-PAN',
      iclRecCompanyCode: '',
      depositRequest: '',
      houseBank: '',
      accountId: '',
      partnerBankId: '',
      enteredBy: 'TREASURY01',
      enteredOn: '28-01-26',
      entryTime: '11:404',
      requestedBy: 'Treasury User',
      requestorCoCode: 'SG03',
      requestorCoName: 'Olam Global Agri Pte. Ltd',
      requestorBank: 'DBS03',
      requestorBankName: 'DBS Bank Singapore',
      expectedDate: '07-02-26',
      lcTenor: '12M',
      businessArea: 'TSF',
      ottkClassification: 'Reference',
      dttkNo: '200005',
      iclRequestStatusDescription: '03 - Approved for ICL Received',
      percentageRate: 5.25,
      fixing: 'Fixed',
      depositCompanyCode: '',
      depositTxn: '',
      wcdlCompanyCode: '',
      iclRecTxn: '',
      iclGivenTxn: '2601000504',
      companyName: 'Olam Global Agri Pte. Ltd',
      activeStatus: 'Active',
      productType: '26A',
      productTypeDescription: 'Inter-Co Loan Given',
      transactionType: '100',
      transactionTypeDescription: 'ICL Given',
      iclReceivedBank: '',
      activeActivity: 'Create',
      businessPartner: 'BP010304',
      profitCenter: 'PC1000',
      profitCenterDescription: 'Treasury Finance',
      businessAreaDescription: 'Trade Structured Finance',
      portfolio: 'PF01',
      accountingCategory: 'AC01',
      iclGivenPrd: '26A',
      iclGivenPrdDesc: 'Inter-Co Loan Given',
      iclRecPrd: '26B',
      iclRecPrdDesc: 'Inter-Co Loan Received',
      targetReceivedCompanyCode: 'AE13',
      dms: {
        docType: 'D01',
        docTypeDesc: 'ICL Received Slip',
        docDate: '',
        filePath: '',
        fileName: '',
        dmsCode: '',
        uploaded: false,
        finalized: false,
      },
    },
    {
      statusCode: 'PENDING',
      client: '300',
      iclGivenCompanyCode: 'SG03',
      iclRequestNo: '22001625',
      requestDate: '28-01-26',
      startDate: '28-01-26',
      endDate: '23-01-27',
      plannedEndDate: '07-02-26',
      amount: 955153.99,
      currency: 'USD',
      dealId: '12001349',
      iclReqStatus: '03',
      ottkNo: '101206',
      slcStructure: 'DSX',
      entityId: 'E021',
      entityString: 'E021 - OGA-DMCC-PAN',
      iclRecCompanyCode: '',
      depositRequest: '',
      houseBank: '',
      accountId: '',
      partnerBankId: '',
      enteredBy: 'TREASURY01',
      enteredOn: '28-01-26',
      entryTime: '11:405',
      requestedBy: 'OIL Treasury',
      requestorCoCode: 'SG03',
      requestorCoName: 'Olam Global Agri Pte. Ltd',
      requestorBank: 'SCB01',
      requestorBankName: 'Standard Chartered Singapore',
      expectedDate: '07-02-26',
      lcTenor: '12M',
      businessArea: 'TSF',
      ottkClassification: 'Reference',
      dttkNo: '',
      iclRequestStatusDescription: '03 - Approved for ICL Received',
      percentageRate: 5.25,
      fixing: 'Float',
      depositCompanyCode: '',
      depositTxn: '',
      wcdlCompanyCode: '',
      iclRecTxn: '',
      iclGivenTxn: '2601000505',
      companyName: 'Olam Global Agri Pte. Ltd',
      activeStatus: 'Active',
      productType: '26A',
      productTypeDescription: 'Inter-Co Loan Given',
      transactionType: '100',
      transactionTypeDescription: 'ICL Given',
      iclReceivedBank: '',
      activeActivity: 'Create',
      businessPartner: 'BP010305',
      profitCenter: 'PC1000',
      profitCenterDescription: 'Treasury Finance',
      businessAreaDescription: 'Trade Structured Finance',
      portfolio: 'PF01',
      accountingCategory: 'AC01',
      iclGivenPrd: '26A',
      iclGivenPrdDesc: 'Inter-Co Loan Given',
      iclRecPrd: '26B',
      iclRecPrdDesc: 'Inter-Co Loan Received',
      targetReceivedCompanyCode: 'AE13',
      dms: {
        docType: 'D01',
        docTypeDesc: 'ICL Received Slip',
        docDate: '',
        filePath: '',
        fileName: '',
        dmsCode: '',
        uploaded: false,
        finalized: false,
      },
    },
    {
      statusCode: 'PENDING',
      client: '300',
      iclGivenCompanyCode: 'SG03',
      iclRequestNo: '22001642',
      requestDate: '04-02-26',
      startDate: '04-02-26',
      endDate: '30-01-27',
      plannedEndDate: '14-02-26',
      amount: 1000000,
      currency: 'USD',
      dealId: '12001369',
      iclReqStatus: '03',
      ottkNo: '101236',
      slcStructure: 'DSX',
      entityId: 'E021',
      entityString: 'E021 - OGA-DMCC-PAN',
      iclRecCompanyCode: '',
      depositRequest: '',
      houseBank: '',
      accountId: '',
      partnerBankId: '',
      enteredBy: 'ALOR',
      enteredOn: '04-02-26',
      entryTime: '11:406',
      requestedBy: 'Treasury User',
      requestorCoCode: 'SG03',
      requestorCoName: 'Olam Global Agri Pte. Ltd',
      requestorBank: 'DBS03',
      requestorBankName: 'DBS Bank Singapore',
      expectedDate: '14-02-26',
      lcTenor: '12M',
      businessArea: 'TSF',
      ottkClassification: 'Direct',
      dttkNo: '',
      iclRequestStatusDescription: '03 - Approved for ICL Received',
      percentageRate: 5.25,
      fixing: 'Fixed',
      depositCompanyCode: '',
      depositTxn: '',
      wcdlCompanyCode: '',
      iclRecTxn: '',
      iclGivenTxn: '2601000506',
      companyName: 'Olam Global Agri Pte. Ltd',
      activeStatus: 'Active',
      productType: '26A',
      productTypeDescription: 'Inter-Co Loan Given',
      transactionType: '100',
      transactionTypeDescription: 'ICL Given',
      iclReceivedBank: '',
      activeActivity: 'Create',
      businessPartner: 'BP010306',
      profitCenter: 'PC1000',
      profitCenterDescription: 'Treasury Finance',
      businessAreaDescription: 'Trade Structured Finance',
      portfolio: 'PF01',
      accountingCategory: 'AC01',
      iclGivenPrd: '26A',
      iclGivenPrdDesc: 'Inter-Co Loan Given',
      iclRecPrd: '26B',
      iclRecPrdDesc: 'Inter-Co Loan Received',
      targetReceivedCompanyCode: 'AE13',
      dms: {
        docType: 'D01',
        docTypeDesc: 'ICL Received Slip',
        docDate: '',
        filePath: '',
        fileName: '',
        dmsCode: '',
        uploaded: false,
        finalized: false,
      },
    },
    {
      statusCode: 'PENDING',
      client: '300',
      iclGivenCompanyCode: 'SG03',
      iclRequestNo: '22001643',
      requestDate: '04-02-26',
      startDate: '04-02-26',
      endDate: '30-01-27',
      plannedEndDate: '14-02-26',
      amount: 1000000,
      currency: 'USD',
      dealId: '12001370',
      iclReqStatus: '03',
      ottkNo: '101237',
      slcStructure: 'DSX',
      entityId: 'E021',
      entityString: 'E021 - OGA-DMCC-PAN',
      iclRecCompanyCode: '',
      depositRequest: '',
      houseBank: '',
      accountId: '',
      partnerBankId: '',
      enteredBy: 'TREASURY01',
      enteredOn: '04-02-26',
      entryTime: '11:407',
      requestedBy: 'OIL Treasury',
      requestorCoCode: 'SG03',
      requestorCoName: 'Olam Global Agri Pte. Ltd',
      requestorBank: 'SCB01',
      requestorBankName: 'Standard Chartered Singapore',
      expectedDate: '14-02-26',
      lcTenor: '12M',
      businessArea: 'TSF',
      ottkClassification: 'Reference',
      dttkNo: '',
      iclRequestStatusDescription: '03 - Approved for ICL Received',
      percentageRate: 5.25,
      fixing: 'Float',
      depositCompanyCode: '',
      depositTxn: '',
      wcdlCompanyCode: '',
      iclRecTxn: '',
      iclGivenTxn: '2601000507',
      companyName: 'Olam Global Agri Pte. Ltd',
      activeStatus: 'Active',
      productType: '26A',
      productTypeDescription: 'Inter-Co Loan Given',
      transactionType: '100',
      transactionTypeDescription: 'ICL Given',
      iclReceivedBank: '',
      activeActivity: 'Create',
      businessPartner: 'BP010307',
      profitCenter: 'PC1000',
      profitCenterDescription: 'Treasury Finance',
      businessAreaDescription: 'Trade Structured Finance',
      portfolio: 'PF01',
      accountingCategory: 'AC01',
      iclGivenPrd: '26A',
      iclGivenPrdDesc: 'Inter-Co Loan Given',
      iclRecPrd: '26B',
      iclRecPrdDesc: 'Inter-Co Loan Received',
      targetReceivedCompanyCode: 'AE13',
      dms: {
        docType: 'D01',
        docTypeDesc: 'ICL Received Slip',
        docDate: '',
        filePath: '',
        fileName: '',
        dmsCode: '',
        uploaded: false,
        finalized: false,
      },
    },
    {
      statusCode: 'PENDING',
      client: '300',
      iclGivenCompanyCode: 'SG03',
      iclRequestNo: '22001623',
      requestDate: '28-01-26',
      startDate: '28-01-26',
      endDate: '23-01-27',
      plannedEndDate: '07-02-26',
      amount: 955153.99,
      currency: 'USD',
      dealId: '12001347',
      iclReqStatus: '03',
      ottkNo: '101204',
      slcStructure: 'DSX',
      entityId: 'E021',
      entityString: 'E021 - OGA-DMCC-PAN',
      iclRecCompanyCode: '',
      depositRequest: '',
      houseBank: '',
      accountId: '',
      partnerBankId: '',
      enteredBy: 'TREASURY01',
      enteredOn: '28-01-26',
      entryTime: '11:408',
      requestedBy: 'Treasury User',
      requestorCoCode: 'SG03',
      requestorCoName: 'Olam Global Agri Pte. Ltd',
      requestorBank: 'DBS03',
      requestorBankName: 'DBS Bank Singapore',
      expectedDate: '07-02-26',
      lcTenor: '12M',
      businessArea: 'TSF',
      ottkClassification: 'Reference',
      dttkNo: '200009',
      iclRequestStatusDescription: '03 - Approved for ICL Received',
      percentageRate: 5.25,
      fixing: 'Fixed',
      depositCompanyCode: '',
      depositTxn: '',
      wcdlCompanyCode: '',
      iclRecTxn: '',
      iclGivenTxn: '2601000508',
      companyName: 'Olam Global Agri Pte. Ltd',
      activeStatus: 'Active',
      productType: '26A',
      productTypeDescription: 'Inter-Co Loan Given',
      transactionType: '100',
      transactionTypeDescription: 'ICL Given',
      iclReceivedBank: '',
      activeActivity: 'Create',
      businessPartner: 'BP010308',
      profitCenter: 'PC1000',
      profitCenterDescription: 'Treasury Finance',
      businessAreaDescription: 'Trade Structured Finance',
      portfolio: 'PF01',
      accountingCategory: 'AC01',
      iclGivenPrd: '26A',
      iclGivenPrdDesc: 'Inter-Co Loan Given',
      iclRecPrd: '26B',
      iclRecPrdDesc: 'Inter-Co Loan Received',
      targetReceivedCompanyCode: 'AE13',
      dms: {
        docType: 'D01',
        docTypeDesc: 'ICL Received Slip',
        docDate: '',
        filePath: '',
        fileName: '',
        dmsCode: '',
        uploaded: false,
        finalized: false,
      },
    },
    {
      statusCode: 'PENDING',
      client: '300',
      iclGivenCompanyCode: 'SG03',
      iclRequestNo: '22001674',
      requestDate: '20-02-26',
      startDate: '20-02-26',
      endDate: '16-12-26',
      plannedEndDate: '13-03-26',
      amount: 47252.78,
      currency: 'USD',
      dealId: '12001446',
      iclReqStatus: '03',
      ottkNo: '101320',
      slcStructure: 'DSX',
      entityId: 'E021',
      entityString: 'E021 - OGA-DMCC-PAN',
      iclRecCompanyCode: '',
      depositRequest: '',
      houseBank: '',
      accountId: '',
      partnerBankId: '',
      enteredBy: 'ALOR',
      enteredOn: '20-02-26',
      entryTime: '11:409',
      requestedBy: 'OIL Treasury',
      requestorCoCode: 'SG03',
      requestorCoName: 'Olam Global Agri Pte. Ltd',
      requestorBank: 'SCB01',
      requestorBankName: 'Standard Chartered Singapore',
      expectedDate: '13-03-26',
      lcTenor: '12M',
      businessArea: 'TSF',
      ottkClassification: 'Direct',
      dttkNo: '',
      iclRequestStatusDescription: '03 - Approved for ICL Received',
      percentageRate: 5.25,
      fixing: 'Float',
      depositCompanyCode: '',
      depositTxn: '',
      wcdlCompanyCode: '',
      iclRecTxn: '',
      iclGivenTxn: '2601000509',
      companyName: 'Olam Global Agri Pte. Ltd',
      activeStatus: 'Active',
      productType: '26A',
      productTypeDescription: 'Inter-Co Loan Given',
      transactionType: '100',
      transactionTypeDescription: 'ICL Given',
      iclReceivedBank: '',
      activeActivity: 'Create',
      businessPartner: 'BP010309',
      profitCenter: 'PC1000',
      profitCenterDescription: 'Treasury Finance',
      businessAreaDescription: 'Trade Structured Finance',
      portfolio: 'PF01',
      accountingCategory: 'AC01',
      iclGivenPrd: '26A',
      iclGivenPrdDesc: 'Inter-Co Loan Given',
      iclRecPrd: '26B',
      iclRecPrdDesc: 'Inter-Co Loan Received',
      targetReceivedCompanyCode: 'AE13',
      dms: {
        docType: 'D01',
        docTypeDesc: 'ICL Received Slip',
        docDate: '',
        filePath: '',
        fileName: '',
        dmsCode: '',
        uploaded: false,
        finalized: false,
      },
    },
    {
      statusCode: 'PENDING',
      client: '300',
      iclGivenCompanyCode: 'SG03',
      iclRequestNo: '22001681',
      requestDate: '20-02-26',
      startDate: '20-02-26',
      endDate: '16-12-26',
      plannedEndDate: '02-03-26',
      amount: 945.06,
      currency: 'USD',
      dealId: '12001448',
      iclReqStatus: '03',
      ottkNo: '101318',
      slcStructure: 'DSX',
      entityId: 'E021',
      entityString: 'E021 - OGA-DMCC-PAN',
      iclRecCompanyCode: '',
      depositRequest: '',
      houseBank: '',
      accountId: '',
      partnerBankId: '',
      enteredBy: 'TREASURY01',
      enteredOn: '20-02-26',
      entryTime: '11:400',
      requestedBy: 'Treasury User',
      requestorCoCode: 'SG03',
      requestorCoName: 'Olam Global Agri Pte. Ltd',
      requestorBank: 'DBS03',
      requestorBankName: 'DBS Bank Singapore',
      expectedDate: '02-03-26',
      lcTenor: '12M',
      businessArea: 'TSF',
      ottkClassification: 'Reference',
      dttkNo: '',
      iclRequestStatusDescription: '03 - Approved for ICL Received',
      percentageRate: 5.25,
      fixing: 'Fixed',
      depositCompanyCode: '',
      depositTxn: '',
      wcdlCompanyCode: '',
      iclRecTxn: '',
      iclGivenTxn: '2601000510',
      companyName: 'Olam Global Agri Pte. Ltd',
      activeStatus: 'Active',
      productType: '26A',
      productTypeDescription: 'Inter-Co Loan Given',
      transactionType: '100',
      transactionTypeDescription: 'ICL Given',
      iclReceivedBank: '',
      activeActivity: 'Create',
      businessPartner: 'BP010310',
      profitCenter: 'PC1000',
      profitCenterDescription: 'Treasury Finance',
      businessAreaDescription: 'Trade Structured Finance',
      portfolio: 'PF01',
      accountingCategory: 'AC01',
      iclGivenPrd: '26A',
      iclGivenPrdDesc: 'Inter-Co Loan Given',
      iclRecPrd: '26B',
      iclRecPrdDesc: 'Inter-Co Loan Received',
      targetReceivedCompanyCode: 'AE13',
      dms: {
        docType: 'D01',
        docTypeDesc: 'ICL Received Slip',
        docDate: '',
        filePath: '',
        fileName: '',
        dmsCode: '',
        uploaded: false,
        finalized: false,
      },
    },
    {
      statusCode: 'PENDING',
      client: '300',
      iclGivenCompanyCode: 'SG03',
      iclRequestNo: '22001695',
      requestDate: '03-03-26',
      startDate: '03-03-26',
      endDate: '14-12-26',
      plannedEndDate: '13-03-26',
      amount: 100,
      currency: 'USD',
      dealId: '12001472',
      iclReqStatus: '03',
      ottkNo: '101348',
      slcStructure: 'DSX',
      entityId: 'E021',
      entityString: 'E021 - OGA-DMCC-PAN',
      iclRecCompanyCode: '',
      depositRequest: '',
      houseBank: '',
      accountId: '',
      partnerBankId: '',
      enteredBy: 'TREASURY01',
      enteredOn: '03-03-26',
      entryTime: '11:401',
      requestedBy: 'OIL Treasury',
      requestorCoCode: 'SG03',
      requestorCoName: 'Olam Global Agri Pte. Ltd',
      requestorBank: 'SCB01',
      requestorBankName: 'Standard Chartered Singapore',
      expectedDate: '13-03-26',
      lcTenor: '12M',
      businessArea: 'TSF',
      ottkClassification: 'Reference',
      dttkNo: '',
      iclRequestStatusDescription: '03 - Approved for ICL Received',
      percentageRate: 5.25,
      fixing: 'Float',
      depositCompanyCode: '',
      depositTxn: '',
      wcdlCompanyCode: '',
      iclRecTxn: '',
      iclGivenTxn: '2601000511',
      companyName: 'Olam Global Agri Pte. Ltd',
      activeStatus: 'Active',
      productType: '26A',
      productTypeDescription: 'Inter-Co Loan Given',
      transactionType: '100',
      transactionTypeDescription: 'ICL Given',
      iclReceivedBank: '',
      activeActivity: 'Create',
      businessPartner: 'BP010311',
      profitCenter: 'PC1000',
      profitCenterDescription: 'Treasury Finance',
      businessAreaDescription: 'Trade Structured Finance',
      portfolio: 'PF01',
      accountingCategory: 'AC01',
      iclGivenPrd: '26A',
      iclGivenPrdDesc: 'Inter-Co Loan Given',
      iclRecPrd: '26B',
      iclRecPrdDesc: 'Inter-Co Loan Received',
      targetReceivedCompanyCode: 'AE13',
      dms: {
        docType: 'D01',
        docTypeDesc: 'ICL Received Slip',
        docDate: '',
        filePath: '',
        fileName: '',
        dmsCode: '',
        uploaded: false,
        finalized: false,
      },
    },
    {
      statusCode: 'PENDING',
      client: '300',
      iclGivenCompanyCode: 'SG03',
      iclRequestNo: '22001641',
      requestDate: '04-02-26',
      startDate: '04-02-26',
      endDate: '30-01-27',
      plannedEndDate: '14-02-26',
      amount: 955153.99,
      currency: 'USD',
      dealId: '12001368',
      iclReqStatus: '03',
      ottkNo: '101235',
      slcStructure: 'DSX',
      entityId: 'E021',
      entityString: 'E021 - OGA-DMCC-PAN',
      iclRecCompanyCode: '',
      depositRequest: '',
      houseBank: '',
      accountId: '',
      partnerBankId: '',
      enteredBy: 'ALOR',
      enteredOn: '04-02-26',
      entryTime: '11:402',
      requestedBy: 'Treasury User',
      requestorCoCode: 'SG03',
      requestorCoName: 'Olam Global Agri Pte. Ltd',
      requestorBank: 'DBS03',
      requestorBankName: 'DBS Bank Singapore',
      expectedDate: '14-02-26',
      lcTenor: '12M',
      businessArea: 'TSF',
      ottkClassification: 'Direct',
      dttkNo: '200013',
      iclRequestStatusDescription: '03 - Approved for ICL Received',
      percentageRate: 5.25,
      fixing: 'Fixed',
      depositCompanyCode: '',
      depositTxn: '',
      wcdlCompanyCode: '',
      iclRecTxn: '',
      iclGivenTxn: '2601000512',
      companyName: 'Olam Global Agri Pte. Ltd',
      activeStatus: 'Active',
      productType: '26A',
      productTypeDescription: 'Inter-Co Loan Given',
      transactionType: '100',
      transactionTypeDescription: 'ICL Given',
      iclReceivedBank: '',
      activeActivity: 'Create',
      businessPartner: 'BP010312',
      profitCenter: 'PC1000',
      profitCenterDescription: 'Treasury Finance',
      businessAreaDescription: 'Trade Structured Finance',
      portfolio: 'PF01',
      accountingCategory: 'AC01',
      iclGivenPrd: '26A',
      iclGivenPrdDesc: 'Inter-Co Loan Given',
      iclRecPrd: '26B',
      iclRecPrdDesc: 'Inter-Co Loan Received',
      targetReceivedCompanyCode: 'AE13',
      dms: {
        docType: 'D01',
        docTypeDesc: 'ICL Received Slip',
        docDate: '',
        filePath: '',
        fileName: '',
        dmsCode: '',
        uploaded: false,
        finalized: false,
      },
    },
    {
      statusCode: 'PENDING',
      client: '300',
      iclGivenCompanyCode: 'SG03',
      iclRequestNo: '22001680',
      requestDate: '20-02-26',
      startDate: '20-02-26',
      endDate: '16-12-26',
      plannedEndDate: '02-03-26',
      amount: 945.06,
      currency: 'USD',
      dealId: '12001447',
      iclReqStatus: '03',
      ottkNo: '101319',
      slcStructure: 'DSX',
      entityId: 'E021',
      entityString: 'E021 - OGA-DMCC-PAN',
      iclRecCompanyCode: '',
      depositRequest: '',
      houseBank: '',
      accountId: '',
      partnerBankId: '',
      enteredBy: 'TREASURY01',
      enteredOn: '20-02-26',
      entryTime: '11:403',
      requestedBy: 'OIL Treasury',
      requestorCoCode: 'SG03',
      requestorCoName: 'Olam Global Agri Pte. Ltd',
      requestorBank: 'SCB01',
      requestorBankName: 'Standard Chartered Singapore',
      expectedDate: '02-03-26',
      lcTenor: '12M',
      businessArea: 'TSF',
      ottkClassification: 'Reference',
      dttkNo: '',
      iclRequestStatusDescription: '03 - Approved for ICL Received',
      percentageRate: 5.25,
      fixing: 'Float',
      depositCompanyCode: '',
      depositTxn: '',
      wcdlCompanyCode: '',
      iclRecTxn: '',
      iclGivenTxn: '2601000513',
      companyName: 'Olam Global Agri Pte. Ltd',
      activeStatus: 'Active',
      productType: '26A',
      productTypeDescription: 'Inter-Co Loan Given',
      transactionType: '100',
      transactionTypeDescription: 'ICL Given',
      iclReceivedBank: '',
      activeActivity: 'Create',
      businessPartner: 'BP010313',
      profitCenter: 'PC1000',
      profitCenterDescription: 'Treasury Finance',
      businessAreaDescription: 'Trade Structured Finance',
      portfolio: 'PF01',
      accountingCategory: 'AC01',
      iclGivenPrd: '26A',
      iclGivenPrdDesc: 'Inter-Co Loan Given',
      iclRecPrd: '26B',
      iclRecPrdDesc: 'Inter-Co Loan Received',
      targetReceivedCompanyCode: 'AE13',
      dms: {
        docType: 'D01',
        docTypeDesc: 'ICL Received Slip',
        docDate: '',
        filePath: '',
        fileName: '',
        dmsCode: '',
        uploaded: false,
        finalized: false,
      },
    },
    {
      statusCode: 'PENDING',
      client: '300',
      iclGivenCompanyCode: 'SG03',
      iclRequestNo: '22001721',
      requestDate: '20-03-26',
      startDate: '20-03-26',
      endDate: '13-01-27',
      plannedEndDate: '30-03-26',
      amount: 9450.56,
      currency: 'USD',
      dealId: '12001549',
      iclReqStatus: '03',
      ottkNo: '101435',
      slcStructure: 'DSX',
      entityId: 'E021',
      entityString: 'E021 - OGA-DMCC-PAN',
      iclRecCompanyCode: '',
      depositRequest: '',
      houseBank: '',
      accountId: '',
      partnerBankId: '',
      enteredBy: 'TREASURY01',
      enteredOn: '20-03-26',
      entryTime: '11:404',
      requestedBy: 'Treasury User',
      requestorCoCode: 'SG03',
      requestorCoName: 'Olam Global Agri Pte. Ltd',
      requestorBank: 'DBS03',
      requestorBankName: 'DBS Bank Singapore',
      expectedDate: '30-03-26',
      lcTenor: '12M',
      businessArea: 'TSF',
      ottkClassification: 'Reference',
      dttkNo: '',
      iclRequestStatusDescription: '03 - Approved for ICL Received',
      percentageRate: 5.25,
      fixing: 'Fixed',
      depositCompanyCode: '',
      depositTxn: '',
      wcdlCompanyCode: '',
      iclRecTxn: '',
      iclGivenTxn: '2601000514',
      companyName: 'Olam Global Agri Pte. Ltd',
      activeStatus: 'Active',
      productType: '26A',
      productTypeDescription: 'Inter-Co Loan Given',
      transactionType: '100',
      transactionTypeDescription: 'ICL Given',
      iclReceivedBank: '',
      activeActivity: 'Create',
      businessPartner: 'BP010314',
      profitCenter: 'PC1000',
      profitCenterDescription: 'Treasury Finance',
      businessAreaDescription: 'Trade Structured Finance',
      portfolio: 'PF01',
      accountingCategory: 'AC01',
      iclGivenPrd: '26A',
      iclGivenPrdDesc: 'Inter-Co Loan Given',
      iclRecPrd: '26B',
      iclRecPrdDesc: 'Inter-Co Loan Received',
      targetReceivedCompanyCode: 'AE13',
      dms: {
        docType: 'D01',
        docTypeDesc: 'ICL Received Slip',
        docDate: '',
        filePath: '',
        fileName: '',
        dmsCode: '',
        uploaded: false,
        finalized: false,
      },
    },
    {
      statusCode: 'PENDING',
      client: '300',
      iclGivenCompanyCode: 'SG03',
      iclRequestNo: '22001722',
      requestDate: '20-03-26',
      startDate: '20-03-26',
      endDate: '13-01-27',
      plannedEndDate: '30-03-26',
      amount: 9450.56,
      currency: 'USD',
      dealId: '12001550',
      iclReqStatus: '03',
      ottkNo: '101436',
      slcStructure: 'DSX',
      entityId: 'E021',
      entityString: 'E021 - OGA-DMCC-PAN',
      iclRecCompanyCode: '',
      depositRequest: '',
      houseBank: '',
      accountId: '',
      partnerBankId: '',
      enteredBy: 'ALOR',
      enteredOn: '20-03-26',
      entryTime: '11:405',
      requestedBy: 'OIL Treasury',
      requestorCoCode: 'SG03',
      requestorCoName: 'Olam Global Agri Pte. Ltd',
      requestorBank: 'SCB01',
      requestorBankName: 'Standard Chartered Singapore',
      expectedDate: '30-03-26',
      lcTenor: '12M',
      businessArea: 'TSF',
      ottkClassification: 'Direct',
      dttkNo: '',
      iclRequestStatusDescription: '03 - Approved for ICL Received',
      percentageRate: 5.25,
      fixing: 'Float',
      depositCompanyCode: '',
      depositTxn: '',
      wcdlCompanyCode: '',
      iclRecTxn: '',
      iclGivenTxn: '2601000515',
      companyName: 'Olam Global Agri Pte. Ltd',
      activeStatus: 'Active',
      productType: '26A',
      productTypeDescription: 'Inter-Co Loan Given',
      transactionType: '100',
      transactionTypeDescription: 'ICL Given',
      iclReceivedBank: '',
      activeActivity: 'Create',
      businessPartner: 'BP010315',
      profitCenter: 'PC1000',
      profitCenterDescription: 'Treasury Finance',
      businessAreaDescription: 'Trade Structured Finance',
      portfolio: 'PF01',
      accountingCategory: 'AC01',
      iclGivenPrd: '26A',
      iclGivenPrdDesc: 'Inter-Co Loan Given',
      iclRecPrd: '26B',
      iclRecPrdDesc: 'Inter-Co Loan Received',
      targetReceivedCompanyCode: 'AE13',
      dms: {
        docType: 'D01',
        docTypeDesc: 'ICL Received Slip',
        docDate: '',
        filePath: '',
        fileName: '',
        dmsCode: '',
        uploaded: false,
        finalized: false,
      },
    },
    {
      statusCode: 'PENDING',
      client: '300',
      iclGivenCompanyCode: 'SG03',
      iclRequestNo: '22001723',
      requestDate: '20-03-26',
      startDate: '20-03-26',
      endDate: '13-01-27',
      plannedEndDate: '30-03-26',
      amount: 9450.56,
      currency: 'USD',
      dealId: '12001551',
      iclReqStatus: '03',
      ottkNo: '101437',
      slcStructure: 'DSX',
      entityId: 'E021',
      entityString: 'E021 - OGA-DMCC-PAN',
      iclRecCompanyCode: '',
      depositRequest: '',
      houseBank: '',
      accountId: '',
      partnerBankId: '',
      enteredBy: 'TREASURY01',
      enteredOn: '20-03-26',
      entryTime: '11:406',
      requestedBy: 'Treasury User',
      requestorCoCode: 'SG03',
      requestorCoName: 'Olam Global Agri Pte. Ltd',
      requestorBank: 'DBS03',
      requestorBankName: 'DBS Bank Singapore',
      expectedDate: '30-03-26',
      lcTenor: '12M',
      businessArea: 'TSF',
      ottkClassification: 'Reference',
      dttkNo: '200017',
      iclRequestStatusDescription: '03 - Approved for ICL Received',
      percentageRate: 5.25,
      fixing: 'Fixed',
      depositCompanyCode: '',
      depositTxn: '',
      wcdlCompanyCode: '',
      iclRecTxn: '',
      iclGivenTxn: '2601000516',
      companyName: 'Olam Global Agri Pte. Ltd',
      activeStatus: 'Active',
      productType: '26A',
      productTypeDescription: 'Inter-Co Loan Given',
      transactionType: '100',
      transactionTypeDescription: 'ICL Given',
      iclReceivedBank: '',
      activeActivity: 'Create',
      businessPartner: 'BP010316',
      profitCenter: 'PC1000',
      profitCenterDescription: 'Treasury Finance',
      businessAreaDescription: 'Trade Structured Finance',
      portfolio: 'PF01',
      accountingCategory: 'AC01',
      iclGivenPrd: '26A',
      iclGivenPrdDesc: 'Inter-Co Loan Given',
      iclRecPrd: '26B',
      iclRecPrdDesc: 'Inter-Co Loan Received',
      targetReceivedCompanyCode: 'AE13',
      dms: {
        docType: 'D01',
        docTypeDesc: 'ICL Received Slip',
        docDate: '',
        filePath: '',
        fileName: '',
        dmsCode: '',
        uploaded: false,
        finalized: false,
      },
    },
    {
      statusCode: 'PENDING',
      client: '300',
      iclGivenCompanyCode: 'SG03',
      iclRequestNo: '22001724',
      requestDate: '20-03-26',
      startDate: '20-03-26',
      endDate: '13-01-27',
      plannedEndDate: '30-03-26',
      amount: 9450.56,
      currency: 'USD',
      dealId: '12001552',
      iclReqStatus: '03',
      ottkNo: '101438',
      slcStructure: 'DSX',
      entityId: 'E021',
      entityString: 'E021 - OGA-DMCC-PAN',
      iclRecCompanyCode: '',
      depositRequest: '',
      houseBank: '',
      accountId: '',
      partnerBankId: '',
      enteredBy: 'TREASURY01',
      enteredOn: '20-03-26',
      entryTime: '11:407',
      requestedBy: 'OIL Treasury',
      requestorCoCode: 'SG03',
      requestorCoName: 'Olam Global Agri Pte. Ltd',
      requestorBank: 'SCB01',
      requestorBankName: 'Standard Chartered Singapore',
      expectedDate: '30-03-26',
      lcTenor: '12M',
      businessArea: 'TSF',
      ottkClassification: 'Reference',
      dttkNo: '',
      iclRequestStatusDescription: '03 - Approved for ICL Received',
      percentageRate: 5.25,
      fixing: 'Float',
      depositCompanyCode: '',
      depositTxn: '',
      wcdlCompanyCode: '',
      iclRecTxn: '',
      iclGivenTxn: '2601000517',
      companyName: 'Olam Global Agri Pte. Ltd',
      activeStatus: 'Active',
      productType: '26A',
      productTypeDescription: 'Inter-Co Loan Given',
      transactionType: '100',
      transactionTypeDescription: 'ICL Given',
      iclReceivedBank: '',
      activeActivity: 'Create',
      businessPartner: 'BP010317',
      profitCenter: 'PC1000',
      profitCenterDescription: 'Treasury Finance',
      businessAreaDescription: 'Trade Structured Finance',
      portfolio: 'PF01',
      accountingCategory: 'AC01',
      iclGivenPrd: '26A',
      iclGivenPrdDesc: 'Inter-Co Loan Given',
      iclRecPrd: '26B',
      iclRecPrdDesc: 'Inter-Co Loan Received',
      targetReceivedCompanyCode: 'AE13',
      dms: {
        docType: 'D01',
        docTypeDesc: 'ICL Received Slip',
        docDate: '',
        filePath: '',
        fileName: '',
        dmsCode: '',
        uploaded: false,
        finalized: false,
      },
    },
    {
      statusCode: 'PENDING',
      client: '300',
      iclGivenCompanyCode: 'SG03',
      iclRequestNo: '22001725',
      requestDate: '20-03-26',
      startDate: '20-03-26',
      endDate: '13-01-27',
      plannedEndDate: '30-03-26',
      amount: 9450.56,
      currency: 'USD',
      dealId: '12001553',
      iclReqStatus: '03',
      ottkNo: '101439',
      slcStructure: 'DSX',
      entityId: 'E021',
      entityString: 'E021 - OGA-DMCC-PAN',
      iclRecCompanyCode: '',
      depositRequest: '',
      houseBank: '',
      accountId: '',
      partnerBankId: '',
      enteredBy: 'ALOR',
      enteredOn: '20-03-26',
      entryTime: '11:408',
      requestedBy: 'Treasury User',
      requestorCoCode: 'SG03',
      requestorCoName: 'Olam Global Agri Pte. Ltd',
      requestorBank: 'DBS03',
      requestorBankName: 'DBS Bank Singapore',
      expectedDate: '30-03-26',
      lcTenor: '12M',
      businessArea: 'TSF',
      ottkClassification: 'Direct',
      dttkNo: '',
      iclRequestStatusDescription: '03 - Approved for ICL Received',
      percentageRate: 5.25,
      fixing: 'Fixed',
      depositCompanyCode: '',
      depositTxn: '',
      wcdlCompanyCode: '',
      iclRecTxn: '',
      iclGivenTxn: '2601000518',
      companyName: 'Olam Global Agri Pte. Ltd',
      activeStatus: 'Active',
      productType: '26A',
      productTypeDescription: 'Inter-Co Loan Given',
      transactionType: '100',
      transactionTypeDescription: 'ICL Given',
      iclReceivedBank: '',
      activeActivity: 'Create',
      businessPartner: 'BP010318',
      profitCenter: 'PC1000',
      profitCenterDescription: 'Treasury Finance',
      businessAreaDescription: 'Trade Structured Finance',
      portfolio: 'PF01',
      accountingCategory: 'AC01',
      iclGivenPrd: '26A',
      iclGivenPrdDesc: 'Inter-Co Loan Given',
      iclRecPrd: '26B',
      iclRecPrdDesc: 'Inter-Co Loan Received',
      targetReceivedCompanyCode: 'AE13',
      dms: {
        docType: 'D01',
        docTypeDesc: 'ICL Received Slip',
        docDate: '',
        filePath: '',
        fileName: '',
        dmsCode: '',
        uploaded: false,
        finalized: false,
      },
    },
    {
      statusCode: 'PENDING',
      client: '300',
      iclGivenCompanyCode: 'SG03',
      iclRequestNo: '22001727',
      requestDate: '20-03-26',
      startDate: '20-03-26',
      endDate: '15-03-27',
      plannedEndDate: '30-03-26',
      amount: 9345.79,
      currency: 'USD',
      dealId: '12001555',
      iclReqStatus: '03',
      ottkNo: '101441',
      slcStructure: 'DSX',
      entityId: 'E021',
      entityString: 'E021 - OGA-DMCC-PAN',
      iclRecCompanyCode: '',
      depositRequest: '',
      houseBank: '',
      accountId: '',
      partnerBankId: '',
      enteredBy: 'TREASURY01',
      enteredOn: '20-03-26',
      entryTime: '11:409',
      requestedBy: 'OIL Treasury',
      requestorCoCode: 'SG03',
      requestorCoName: 'Olam Global Agri Pte. Ltd',
      requestorBank: 'SCB01',
      requestorBankName: 'Standard Chartered Singapore',
      expectedDate: '30-03-26',
      lcTenor: '12M',
      businessArea: 'TSF',
      ottkClassification: 'Reference',
      dttkNo: '',
      iclRequestStatusDescription: '03 - Approved for ICL Received',
      percentageRate: 5.25,
      fixing: 'Float',
      depositCompanyCode: '',
      depositTxn: '',
      wcdlCompanyCode: '',
      iclRecTxn: '',
      iclGivenTxn: '2601000519',
      companyName: 'Olam Global Agri Pte. Ltd',
      activeStatus: 'Active',
      productType: '26A',
      productTypeDescription: 'Inter-Co Loan Given',
      transactionType: '100',
      transactionTypeDescription: 'ICL Given',
      iclReceivedBank: '',
      activeActivity: 'Create',
      businessPartner: 'BP010319',
      profitCenter: 'PC1000',
      profitCenterDescription: 'Treasury Finance',
      businessAreaDescription: 'Trade Structured Finance',
      portfolio: 'PF01',
      accountingCategory: 'AC01',
      iclGivenPrd: '26A',
      iclGivenPrdDesc: 'Inter-Co Loan Given',
      iclRecPrd: '26B',
      iclRecPrdDesc: 'Inter-Co Loan Received',
      targetReceivedCompanyCode: 'AE13',
      dms: {
        docType: 'D01',
        docTypeDesc: 'ICL Received Slip',
        docDate: '',
        filePath: '',
        fileName: '',
        dmsCode: '',
        uploaded: false,
        finalized: false,
      },
    },
    {
      statusCode: 'PENDING',
      client: '300',
      iclGivenCompanyCode: 'SG03',
      iclRequestNo: '22001728',
      requestDate: '20-03-26',
      startDate: '20-03-26',
      endDate: '15-03-27',
      plannedEndDate: '30-03-26',
      amount: 9345.79,
      currency: 'USD',
      dealId: '12001556',
      iclReqStatus: '03',
      ottkNo: '101442',
      slcStructure: 'DSX',
      entityId: 'E021',
      entityString: 'E021 - OGA-DMCC-PAN',
      iclRecCompanyCode: '',
      depositRequest: '',
      houseBank: '',
      accountId: '',
      partnerBankId: '',
      enteredBy: 'TREASURY01',
      enteredOn: '20-03-26',
      entryTime: '11:400',
      requestedBy: 'Treasury User',
      requestorCoCode: 'SG03',
      requestorCoName: 'Olam Global Agri Pte. Ltd',
      requestorBank: 'DBS03',
      requestorBankName: 'DBS Bank Singapore',
      expectedDate: '30-03-26',
      lcTenor: '12M',
      businessArea: 'TSF',
      ottkClassification: 'Reference',
      dttkNo: '200021',
      iclRequestStatusDescription: '03 - Approved for ICL Received',
      percentageRate: 5.25,
      fixing: 'Fixed',
      depositCompanyCode: '',
      depositTxn: '',
      wcdlCompanyCode: '',
      iclRecTxn: '',
      iclGivenTxn: '2601000520',
      companyName: 'Olam Global Agri Pte. Ltd',
      activeStatus: 'Active',
      productType: '26A',
      productTypeDescription: 'Inter-Co Loan Given',
      transactionType: '100',
      transactionTypeDescription: 'ICL Given',
      iclReceivedBank: '',
      activeActivity: 'Create',
      businessPartner: 'BP010320',
      profitCenter: 'PC1000',
      profitCenterDescription: 'Treasury Finance',
      businessAreaDescription: 'Trade Structured Finance',
      portfolio: 'PF01',
      accountingCategory: 'AC01',
      iclGivenPrd: '26A',
      iclGivenPrdDesc: 'Inter-Co Loan Given',
      iclRecPrd: '26B',
      iclRecPrdDesc: 'Inter-Co Loan Received',
      targetReceivedCompanyCode: 'AE13',
      dms: {
        docType: 'D01',
        docTypeDesc: 'ICL Received Slip',
        docDate: '',
        filePath: '',
        fileName: '',
        dmsCode: '',
        uploaded: false,
        finalized: false,
      },
    },
    {
      statusCode: 'PENDING',
      client: '300',
      iclGivenCompanyCode: 'SG03',
      iclRequestNo: '22001732',
      requestDate: '24-03-26',
      startDate: '24-03-26',
      endDate: '19-03-27',
      plannedEndDate: '03-04-26',
      amount: 9345.79,
      currency: 'USD',
      dealId: '12001565',
      iclReqStatus: '03',
      ottkNo: '101459',
      slcStructure: 'DSX',
      entityId: 'E021',
      entityString: 'E021 - OGA-DMCC-PAN',
      iclRecCompanyCode: '',
      depositRequest: '',
      houseBank: '',
      accountId: '',
      partnerBankId: '',
      enteredBy: 'ALOR',
      enteredOn: '24-03-26',
      entryTime: '11:401',
      requestedBy: 'OIL Treasury',
      requestorCoCode: 'SG03',
      requestorCoName: 'Olam Global Agri Pte. Ltd',
      requestorBank: 'SCB01',
      requestorBankName: 'Standard Chartered Singapore',
      expectedDate: '03-04-26',
      lcTenor: '12M',
      businessArea: 'TSF',
      ottkClassification: 'Direct',
      dttkNo: '',
      iclRequestStatusDescription: '03 - Approved for ICL Received',
      percentageRate: 5.25,
      fixing: 'Float',
      depositCompanyCode: '',
      depositTxn: '',
      wcdlCompanyCode: '',
      iclRecTxn: '',
      iclGivenTxn: '2601000521',
      companyName: 'Olam Global Agri Pte. Ltd',
      activeStatus: 'Active',
      productType: '26A',
      productTypeDescription: 'Inter-Co Loan Given',
      transactionType: '100',
      transactionTypeDescription: 'ICL Given',
      iclReceivedBank: '',
      activeActivity: 'Create',
      businessPartner: 'BP010321',
      profitCenter: 'PC1000',
      profitCenterDescription: 'Treasury Finance',
      businessAreaDescription: 'Trade Structured Finance',
      portfolio: 'PF01',
      accountingCategory: 'AC01',
      iclGivenPrd: '26A',
      iclGivenPrdDesc: 'Inter-Co Loan Given',
      iclRecPrd: '26B',
      iclRecPrdDesc: 'Inter-Co Loan Received',
      targetReceivedCompanyCode: 'AE13',
      dms: {
        docType: 'D01',
        docTypeDesc: 'ICL Received Slip',
        docDate: '',
        filePath: '',
        fileName: '',
        dmsCode: '',
        uploaded: false,
        finalized: false,
      },
    },
    {
      statusCode: 'PENDING',
      client: '300',
      iclGivenCompanyCode: 'SG03',
      iclRequestNo: '22001733',
      requestDate: '24-03-26',
      startDate: '24-03-26',
      endDate: '19-03-27',
      plannedEndDate: '03-04-26',
      amount: 9345.79,
      currency: 'USD',
      dealId: '12001566',
      iclReqStatus: '03',
      ottkNo: '101460',
      slcStructure: 'DSX',
      entityId: 'E021',
      entityString: 'E021 - OGA-DMCC-PAN',
      iclRecCompanyCode: '',
      depositRequest: '',
      houseBank: '',
      accountId: '',
      partnerBankId: '',
      enteredBy: 'TREASURY01',
      enteredOn: '24-03-26',
      entryTime: '11:402',
      requestedBy: 'Treasury User',
      requestorCoCode: 'SG03',
      requestorCoName: 'Olam Global Agri Pte. Ltd',
      requestorBank: 'DBS03',
      requestorBankName: 'DBS Bank Singapore',
      expectedDate: '03-04-26',
      lcTenor: '12M',
      businessArea: 'TSF',
      ottkClassification: 'Reference',
      dttkNo: '',
      iclRequestStatusDescription: '03 - Approved for ICL Received',
      percentageRate: 5.25,
      fixing: 'Fixed',
      depositCompanyCode: '',
      depositTxn: '',
      wcdlCompanyCode: '',
      iclRecTxn: '',
      iclGivenTxn: '2601000522',
      companyName: 'Olam Global Agri Pte. Ltd',
      activeStatus: 'Active',
      productType: '26A',
      productTypeDescription: 'Inter-Co Loan Given',
      transactionType: '100',
      transactionTypeDescription: 'ICL Given',
      iclReceivedBank: '',
      activeActivity: 'Create',
      businessPartner: 'BP010322',
      profitCenter: 'PC1000',
      profitCenterDescription: 'Treasury Finance',
      businessAreaDescription: 'Trade Structured Finance',
      portfolio: 'PF01',
      accountingCategory: 'AC01',
      iclGivenPrd: '26A',
      iclGivenPrdDesc: 'Inter-Co Loan Given',
      iclRecPrd: '26B',
      iclRecPrdDesc: 'Inter-Co Loan Received',
      targetReceivedCompanyCode: 'AE13',
      dms: {
        docType: 'D01',
        docTypeDesc: 'ICL Received Slip',
        docDate: '',
        filePath: '',
        fileName: '',
        dmsCode: '',
        uploaded: false,
        finalized: false,
      },
    },
    {
      statusCode: 'PENDING',
      client: '300',
      iclGivenCompanyCode: 'SG03',
      iclRequestNo: '22001734',
      requestDate: '24-03-26',
      startDate: '24-03-26',
      endDate: '19-03-27',
      plannedEndDate: '03-04-26',
      amount: 9345.79,
      currency: 'USD',
      dealId: '12001567',
      iclReqStatus: '03',
      ottkNo: '101461',
      slcStructure: 'DSX',
      entityId: 'E021',
      entityString: 'E021 - OGA-DMCC-PAN',
      iclRecCompanyCode: '',
      depositRequest: '',
      houseBank: '',
      accountId: '',
      partnerBankId: '',
      enteredBy: 'TREASURY01',
      enteredOn: '24-03-26',
      entryTime: '11:403',
      requestedBy: 'OIL Treasury',
      requestorCoCode: 'SG03',
      requestorCoName: 'Olam Global Agri Pte. Ltd',
      requestorBank: 'SCB01',
      requestorBankName: 'Standard Chartered Singapore',
      expectedDate: '03-04-26',
      lcTenor: '12M',
      businessArea: 'TSF',
      ottkClassification: 'Reference',
      dttkNo: '',
      iclRequestStatusDescription: '03 - Approved for ICL Received',
      percentageRate: 5.25,
      fixing: 'Float',
      depositCompanyCode: '',
      depositTxn: '',
      wcdlCompanyCode: '',
      iclRecTxn: '',
      iclGivenTxn: '2601000523',
      companyName: 'Olam Global Agri Pte. Ltd',
      activeStatus: 'Active',
      productType: '26A',
      productTypeDescription: 'Inter-Co Loan Given',
      transactionType: '100',
      transactionTypeDescription: 'ICL Given',
      iclReceivedBank: '',
      activeActivity: 'Create',
      businessPartner: 'BP010323',
      profitCenter: 'PC1000',
      profitCenterDescription: 'Treasury Finance',
      businessAreaDescription: 'Trade Structured Finance',
      portfolio: 'PF01',
      accountingCategory: 'AC01',
      iclGivenPrd: '26A',
      iclGivenPrdDesc: 'Inter-Co Loan Given',
      iclRecPrd: '26B',
      iclRecPrdDesc: 'Inter-Co Loan Received',
      targetReceivedCompanyCode: 'AE13',
      dms: {
        docType: 'D01',
        docTypeDesc: 'ICL Received Slip',
        docDate: '',
        filePath: '',
        fileName: '',
        dmsCode: '',
        uploaded: false,
        finalized: false,
      },
    },
    {
      statusCode: 'PENDING',
      client: '300',
      iclGivenCompanyCode: 'SG03',
      iclRequestNo: '22001632',
      requestDate: '02-02-26',
      startDate: '01-12-25',
      endDate: '26-11-26',
      plannedEndDate: '11-12-25',
      amount: 47800,
      currency: 'USD',
      dealId: '12001090',
      iclReqStatus: '03',
      ottkNo: '100912',
      slcStructure: 'DSX',
      entityId: 'E021',
      entityString: 'E021 - OGA-DMCC-PAN',
      iclRecCompanyCode: '',
      depositRequest: '',
      houseBank: '',
      accountId: '',
      partnerBankId: '',
      enteredBy: 'ALOR',
      enteredOn: '02-02-26',
      entryTime: '11:404',
      requestedBy: 'Treasury User',
      requestorCoCode: 'SG03',
      requestorCoName: 'Olam Global Agri Pte. Ltd',
      requestorBank: 'DBS03',
      requestorBankName: 'DBS Bank Singapore',
      expectedDate: '11-12-25',
      lcTenor: '12M',
      businessArea: 'TSF',
      ottkClassification: 'Direct',
      dttkNo: '200025',
      iclRequestStatusDescription: '03 - Approved for ICL Received',
      percentageRate: 5.25,
      fixing: 'Fixed',
      depositCompanyCode: '',
      depositTxn: '',
      wcdlCompanyCode: '',
      iclRecTxn: '',
      iclGivenTxn: '2601000524',
      companyName: 'Olam Global Agri Pte. Ltd',
      activeStatus: 'Active',
      productType: '26A',
      productTypeDescription: 'Inter-Co Loan Given',
      transactionType: '100',
      transactionTypeDescription: 'ICL Given',
      iclReceivedBank: '',
      activeActivity: 'Create',
      businessPartner: 'BP010324',
      profitCenter: 'PC1000',
      profitCenterDescription: 'Treasury Finance',
      businessAreaDescription: 'Trade Structured Finance',
      portfolio: 'PF01',
      accountingCategory: 'AC01',
      iclGivenPrd: '26A',
      iclGivenPrdDesc: 'Inter-Co Loan Given',
      iclRecPrd: '26B',
      iclRecPrdDesc: 'Inter-Co Loan Received',
      targetReceivedCompanyCode: 'AE13',
      dms: {
        docType: 'D01',
        docTypeDesc: 'ICL Received Slip',
        docDate: '',
        filePath: '',
        fileName: '',
        dmsCode: '',
        uploaded: false,
        finalized: false,
      },
    },
    {
      statusCode: 'PENDING',
      client: '300',
      iclGivenCompanyCode: 'SG03',
      iclRequestNo: '22001720',
      requestDate: '20-03-26',
      startDate: '20-03-26',
      endDate: '13-01-27',
      plannedEndDate: '30-03-26',
      amount: 9450.56,
      currency: 'USD',
      dealId: '12001548',
      iclReqStatus: '03',
      ottkNo: '101434',
      slcStructure: 'DSX',
      entityId: 'E021',
      entityString: 'E021 - OGA-DMCC-PAN',
      iclRecCompanyCode: '',
      depositRequest: '',
      houseBank: '',
      accountId: '',
      partnerBankId: '',
      enteredBy: 'TREASURY01',
      enteredOn: '20-03-26',
      entryTime: '11:405',
      requestedBy: 'OIL Treasury',
      requestorCoCode: 'SG03',
      requestorCoName: 'Olam Global Agri Pte. Ltd',
      requestorBank: 'SCB01',
      requestorBankName: 'Standard Chartered Singapore',
      expectedDate: '30-03-26',
      lcTenor: '12M',
      businessArea: 'TSF',
      ottkClassification: 'Reference',
      dttkNo: '',
      iclRequestStatusDescription: '03 - Approved for ICL Received',
      percentageRate: 5.25,
      fixing: 'Float',
      depositCompanyCode: '',
      depositTxn: '',
      wcdlCompanyCode: '',
      iclRecTxn: '',
      iclGivenTxn: '2601000525',
      companyName: 'Olam Global Agri Pte. Ltd',
      activeStatus: 'Active',
      productType: '26A',
      productTypeDescription: 'Inter-Co Loan Given',
      transactionType: '100',
      transactionTypeDescription: 'ICL Given',
      iclReceivedBank: '',
      activeActivity: 'Create',
      businessPartner: 'BP010325',
      profitCenter: 'PC1000',
      profitCenterDescription: 'Treasury Finance',
      businessAreaDescription: 'Trade Structured Finance',
      portfolio: 'PF01',
      accountingCategory: 'AC01',
      iclGivenPrd: '26A',
      iclGivenPrdDesc: 'Inter-Co Loan Given',
      iclRecPrd: '26B',
      iclRecPrdDesc: 'Inter-Co Loan Received',
      targetReceivedCompanyCode: 'AE13',
      dms: {
        docType: 'D01',
        docTypeDesc: 'ICL Received Slip',
        docDate: '',
        filePath: '',
        fileName: '',
        dmsCode: '',
        uploaded: false,
        finalized: false,
      },
    },
    {
      statusCode: 'PENDING',
      client: '300',
      iclGivenCompanyCode: 'SG03',
      iclRequestNo: '22001735',
      requestDate: '24-03-26',
      startDate: '11-12-25',
      endDate: '06-12-26',
      plannedEndDate: '21-12-25',
      amount: 93457.94,
      currency: 'USD',
      dealId: '',
      iclReqStatus: '03',
      ottkNo: '101462',
      slcStructure: 'DSX',
      entityId: 'E021',
      entityString: 'E021 - OGA-DMCC-PAN',
      iclRecCompanyCode: '',
      depositRequest: '',
      houseBank: '',
      accountId: '',
      partnerBankId: '',
      enteredBy: 'TREASURY01',
      enteredOn: '24-03-26',
      entryTime: '11:406',
      requestedBy: 'Treasury User',
      requestorCoCode: 'SG03',
      requestorCoName: 'Olam Global Agri Pte. Ltd',
      requestorBank: 'DBS03',
      requestorBankName: 'DBS Bank Singapore',
      expectedDate: '21-12-25',
      lcTenor: '12M',
      businessArea: 'TSF',
      ottkClassification: 'Reference',
      dttkNo: '',
      iclRequestStatusDescription: '03 - Approved for ICL Received',
      percentageRate: 5.25,
      fixing: 'Fixed',
      depositCompanyCode: '',
      depositTxn: '',
      wcdlCompanyCode: '',
      iclRecTxn: '',
      iclGivenTxn: '2601000526',
      companyName: 'Olam Global Agri Pte. Ltd',
      activeStatus: 'Active',
      productType: '26A',
      productTypeDescription: 'Inter-Co Loan Given',
      transactionType: '100',
      transactionTypeDescription: 'ICL Given',
      iclReceivedBank: '',
      activeActivity: 'Create',
      businessPartner: 'BP010326',
      profitCenter: 'PC1000',
      profitCenterDescription: 'Treasury Finance',
      businessAreaDescription: 'Trade Structured Finance',
      portfolio: 'PF01',
      accountingCategory: 'AC01',
      iclGivenPrd: '26A',
      iclGivenPrdDesc: 'Inter-Co Loan Given',
      iclRecPrd: '26B',
      iclRecPrdDesc: 'Inter-Co Loan Received',
      targetReceivedCompanyCode: 'AE13',
      dms: {
        docType: 'D01',
        docTypeDesc: 'ICL Received Slip',
        docDate: '',
        filePath: '',
        fileName: '',
        dmsCode: '',
        uploaded: false,
        finalized: false,
      },
    },
    {
      statusCode: 'PENDING',
      client: '300',
      iclGivenCompanyCode: 'SG03',
      iclRequestNo: '22001767',
      requestDate: '29-06-26',
      startDate: '08-06-26',
      endDate: '30-06-26',
      plannedEndDate: '30-06-26',
      amount: 9000,
      currency: 'USD',
      dealId: '14000637',
      iclReqStatus: '03',
      ottkNo: '400632',
      slcStructure: 'ICFSI',
      entityId: 'E103',
      entityString: 'E103 - VEND-OAL-CUST',
      iclRecCompanyCode: '',
      depositRequest: '',
      houseBank: '',
      accountId: '',
      partnerBankId: '',
      enteredBy: 'ALOR',
      enteredOn: '29-06-26',
      entryTime: '11:407',
      requestedBy: 'OIL Treasury',
      requestorCoCode: 'SG03',
      requestorCoName: 'Olam Global Agri Pte. Ltd',
      requestorBank: 'SCB01',
      requestorBankName: 'Standard Chartered Singapore',
      expectedDate: '30-06-26',
      lcTenor: '6M',
      businessArea: 'TSF',
      ottkClassification: 'Direct',
      dttkNo: '',
      iclRequestStatusDescription: '03 - Approved for ICL Received',
      percentageRate: 4.75,
      fixing: 'Float',
      depositCompanyCode: '',
      depositTxn: '',
      wcdlCompanyCode: '',
      iclRecTxn: '',
      iclGivenTxn: '2601000527',
      companyName: 'Olam Global Agri Pte. Ltd',
      activeStatus: 'Active',
      productType: '26A',
      productTypeDescription: 'Inter-Co Loan Given',
      transactionType: '100',
      transactionTypeDescription: 'ICL Given',
      iclReceivedBank: '',
      activeActivity: 'Create',
      businessPartner: 'BP010327',
      profitCenter: 'PC2000',
      profitCenterDescription: 'Vendor Financing',
      businessAreaDescription: 'Trade Structured Finance',
      portfolio: 'PF01',
      accountingCategory: 'AC01',
      iclGivenPrd: '26A',
      iclGivenPrdDesc: 'Inter-Co Loan Given',
      iclRecPrd: '26B',
      iclRecPrdDesc: 'Inter-Co Loan Received',
      targetReceivedCompanyCode: 'AE13',
      dms: {
        docType: 'D01',
        docTypeDesc: 'ICL Received Slip',
        docDate: '',
        filePath: '',
        fileName: '',
        dmsCode: '',
        uploaded: false,
        finalized: false,
      },
    },
    {
      statusCode: 'PENDING',
      client: '300',
      iclGivenCompanyCode: 'SG03',
      iclRequestNo: '22001768',
      requestDate: '30-06-26',
      startDate: '08-06-26',
      endDate: '30-06-26',
      plannedEndDate: '30-06-26',
      amount: 9000,
      currency: 'USD',
      dealId: '14000638',
      iclReqStatus: '03',
      ottkNo: '400633',
      slcStructure: 'ICFSI',
      entityId: 'E103',
      entityString: 'E103 - VEND-OAL-CUST',
      iclRecCompanyCode: '',
      depositRequest: '',
      houseBank: '',
      accountId: '',
      partnerBankId: '',
      enteredBy: 'TREASURY01',
      enteredOn: '30-06-26',
      entryTime: '11:408',
      requestedBy: 'Treasury User',
      requestorCoCode: 'SG03',
      requestorCoName: 'Olam Global Agri Pte. Ltd',
      requestorBank: 'DBS03',
      requestorBankName: 'DBS Bank Singapore',
      expectedDate: '30-06-26',
      lcTenor: '6M',
      businessArea: 'TSF',
      ottkClassification: 'Reference',
      dttkNo: '200029',
      iclRequestStatusDescription: '03 - Approved for ICL Received',
      percentageRate: 4.75,
      fixing: 'Fixed',
      depositCompanyCode: '',
      depositTxn: '',
      wcdlCompanyCode: '',
      iclRecTxn: '',
      iclGivenTxn: '2601000528',
      companyName: 'Olam Global Agri Pte. Ltd',
      activeStatus: 'Active',
      productType: '26A',
      productTypeDescription: 'Inter-Co Loan Given',
      transactionType: '100',
      transactionTypeDescription: 'ICL Given',
      iclReceivedBank: '',
      activeActivity: 'Create',
      businessPartner: 'BP010328',
      profitCenter: 'PC2000',
      profitCenterDescription: 'Vendor Financing',
      businessAreaDescription: 'Trade Structured Finance',
      portfolio: 'PF01',
      accountingCategory: 'AC01',
      iclGivenPrd: '26A',
      iclGivenPrdDesc: 'Inter-Co Loan Given',
      iclRecPrd: '26B',
      iclRecPrdDesc: 'Inter-Co Loan Received',
      targetReceivedCompanyCode: 'AE13',
      dms: {
        docType: 'D01',
        docTypeDesc: 'ICL Received Slip',
        docDate: '',
        filePath: '',
        fileName: '',
        dmsCode: '',
        uploaded: false,
        finalized: false,
      },
    },
    {
      statusCode: 'PENDING',
      client: '300',
      iclGivenCompanyCode: 'SG03',
      iclRequestNo: '22001736',
      requestDate: '24-03-26',
      startDate: '24-03-26',
      endDate: '19-03-27',
      plannedEndDate: '03-04-26',
      amount: 9345.79,
      currency: 'USD',
      dealId: '',
      iclReqStatus: '03',
      ottkNo: '101463',
      slcStructure: 'DSX',
      entityId: 'E021',
      entityString: 'E021 - OGA-DMCC-PAN',
      iclRecCompanyCode: '',
      depositRequest: '',
      houseBank: '',
      accountId: '',
      partnerBankId: '',
      enteredBy: 'TREASURY01',
      enteredOn: '24-03-26',
      entryTime: '11:409',
      requestedBy: 'OIL Treasury',
      requestorCoCode: 'SG03',
      requestorCoName: 'Olam Global Agri Pte. Ltd',
      requestorBank: 'SCB01',
      requestorBankName: 'Standard Chartered Singapore',
      expectedDate: '03-04-26',
      lcTenor: '12M',
      businessArea: 'TSF',
      ottkClassification: 'Reference',
      dttkNo: '',
      iclRequestStatusDescription: '03 - Approved for ICL Received',
      percentageRate: 5.25,
      fixing: 'Float',
      depositCompanyCode: '',
      depositTxn: '',
      wcdlCompanyCode: '',
      iclRecTxn: '',
      iclGivenTxn: '2601000529',
      companyName: 'Olam Global Agri Pte. Ltd',
      activeStatus: 'Active',
      productType: '26A',
      productTypeDescription: 'Inter-Co Loan Given',
      transactionType: '100',
      transactionTypeDescription: 'ICL Given',
      iclReceivedBank: '',
      activeActivity: 'Create',
      businessPartner: 'BP010329',
      profitCenter: 'PC1000',
      profitCenterDescription: 'Treasury Finance',
      businessAreaDescription: 'Trade Structured Finance',
      portfolio: 'PF01',
      accountingCategory: 'AC01',
      iclGivenPrd: '26A',
      iclGivenPrdDesc: 'Inter-Co Loan Given',
      iclRecPrd: '26B',
      iclRecPrdDesc: 'Inter-Co Loan Received',
      targetReceivedCompanyCode: 'AE13',
      dms: {
        docType: 'D01',
        docTypeDesc: 'ICL Received Slip',
        docDate: '',
        filePath: '',
        fileName: '',
        dmsCode: '',
        uploaded: false,
        finalized: false,
      },
    },
    {
      statusCode: 'PENDING',
      client: '300',
      iclGivenCompanyCode: 'SG03',
      iclRequestNo: '22001737',
      requestDate: '24-03-26',
      startDate: '24-03-26',
      endDate: '19-03-27',
      plannedEndDate: '03-04-26',
      amount: 9345.79,
      currency: 'USD',
      dealId: '',
      iclReqStatus: '03',
      ottkNo: '101464',
      slcStructure: 'DSX',
      entityId: 'E021',
      entityString: 'E021 - OGA-DMCC-PAN',
      iclRecCompanyCode: '',
      depositRequest: '',
      houseBank: '',
      accountId: '',
      partnerBankId: '',
      enteredBy: 'ALOR',
      enteredOn: '24-03-26',
      entryTime: '11:400',
      requestedBy: 'Treasury User',
      requestorCoCode: 'SG03',
      requestorCoName: 'Olam Global Agri Pte. Ltd',
      requestorBank: 'DBS03',
      requestorBankName: 'DBS Bank Singapore',
      expectedDate: '03-04-26',
      lcTenor: '12M',
      businessArea: 'TSF',
      ottkClassification: 'Direct',
      dttkNo: '',
      iclRequestStatusDescription: '03 - Approved for ICL Received',
      percentageRate: 5.25,
      fixing: 'Fixed',
      depositCompanyCode: '',
      depositTxn: '',
      wcdlCompanyCode: '',
      iclRecTxn: '',
      iclGivenTxn: '2601000530',
      companyName: 'Olam Global Agri Pte. Ltd',
      activeStatus: 'Active',
      productType: '26A',
      productTypeDescription: 'Inter-Co Loan Given',
      transactionType: '100',
      transactionTypeDescription: 'ICL Given',
      iclReceivedBank: '',
      activeActivity: 'Create',
      businessPartner: 'BP010330',
      profitCenter: 'PC1000',
      profitCenterDescription: 'Treasury Finance',
      businessAreaDescription: 'Trade Structured Finance',
      portfolio: 'PF01',
      accountingCategory: 'AC01',
      iclGivenPrd: '26A',
      iclGivenPrdDesc: 'Inter-Co Loan Given',
      iclRecPrd: '26B',
      iclRecPrdDesc: 'Inter-Co Loan Received',
      targetReceivedCompanyCode: 'AE13',
      dms: {
        docType: 'D01',
        docTypeDesc: 'ICL Received Slip',
        docDate: '',
        filePath: '',
        fileName: '',
        dmsCode: '',
        uploaded: false,
        finalized: false,
      },
    },
    {
      statusCode: 'PENDING',
      client: '300',
      iclGivenCompanyCode: 'SG03',
      iclRequestNo: '22001800',
      requestDate: '05-08-26',
      startDate: '24-03-26',
      endDate: '19-03-27',
      plannedEndDate: '03-04-26',
      amount: 9345.79,
      currency: 'USD',
      dealId: '',
      iclReqStatus: '03',
      ottkNo: '101622',
      slcStructure: 'DSX',
      entityId: 'E021',
      entityString: 'E021 - OGA-DMCC-PAN',
      iclRecCompanyCode: '',
      depositRequest: '',
      houseBank: '',
      accountId: '',
      partnerBankId: '',
      enteredBy: 'TREASURY01',
      enteredOn: '05-08-26',
      entryTime: '11:401',
      requestedBy: 'OIL Treasury',
      requestorCoCode: 'SG03',
      requestorCoName: 'Olam Global Agri Pte. Ltd',
      requestorBank: 'SCB01',
      requestorBankName: 'Standard Chartered Singapore',
      expectedDate: '03-04-26',
      lcTenor: '12M',
      businessArea: 'TSF',
      ottkClassification: 'Reference',
      dttkNo: '',
      iclRequestStatusDescription: '03 - Approved for ICL Received',
      percentageRate: 5.25,
      fixing: 'Float',
      depositCompanyCode: '',
      depositTxn: '',
      wcdlCompanyCode: '',
      iclRecTxn: '',
      iclGivenTxn: '2601000531',
      companyName: 'Olam Global Agri Pte. Ltd',
      activeStatus: 'Active',
      productType: '26A',
      productTypeDescription: 'Inter-Co Loan Given',
      transactionType: '100',
      transactionTypeDescription: 'ICL Given',
      iclReceivedBank: '',
      activeActivity: 'Create',
      businessPartner: 'BP010331',
      profitCenter: 'PC1000',
      profitCenterDescription: 'Treasury Finance',
      businessAreaDescription: 'Trade Structured Finance',
      portfolio: 'PF01',
      accountingCategory: 'AC01',
      iclGivenPrd: '26A',
      iclGivenPrdDesc: 'Inter-Co Loan Given',
      iclRecPrd: '26B',
      iclRecPrdDesc: 'Inter-Co Loan Received',
      targetReceivedCompanyCode: 'AE13',
      dms: {
        docType: 'D01',
        docTypeDesc: 'ICL Received Slip',
        docDate: '',
        filePath: '',
        fileName: '',
        dmsCode: '',
        uploaded: false,
        finalized: false,
      },
    },
    {
      statusCode: 'PENDING',
      client: '300',
      iclGivenCompanyCode: 'SG03',
      iclRequestNo: '22001829',
      requestDate: '12-08-26',
      startDate: '11-08-26',
      endDate: '06-08-27',
      plannedEndDate: '21-08-26',
      amount: 9345.79,
      currency: 'USD',
      dealId: '',
      iclReqStatus: '03',
      ottkNo: '101696',
      slcStructure: 'DSX',
      entityId: 'E021',
      entityString: 'E021 - OGA-DMCC-PAN',
      iclRecCompanyCode: '',
      depositRequest: '',
      houseBank: '',
      accountId: '',
      partnerBankId: '',
      enteredBy: 'TREASURY01',
      enteredOn: '12-08-26',
      entryTime: '11:402',
      requestedBy: 'Treasury User',
      requestorCoCode: 'SG03',
      requestorCoName: 'Olam Global Agri Pte. Ltd',
      requestorBank: 'DBS03',
      requestorBankName: 'DBS Bank Singapore',
      expectedDate: '21-08-26',
      lcTenor: '12M',
      businessArea: 'TSF',
      ottkClassification: 'Reference',
      dttkNo: '200033',
      iclRequestStatusDescription: '03 - Approved for ICL Received',
      percentageRate: 5.25,
      fixing: 'Fixed',
      depositCompanyCode: '',
      depositTxn: '',
      wcdlCompanyCode: '',
      iclRecTxn: '',
      iclGivenTxn: '2601000532',
      companyName: 'Olam Global Agri Pte. Ltd',
      activeStatus: 'Active',
      productType: '26A',
      productTypeDescription: 'Inter-Co Loan Given',
      transactionType: '100',
      transactionTypeDescription: 'ICL Given',
      iclReceivedBank: '',
      activeActivity: 'Create',
      businessPartner: 'BP010332',
      profitCenter: 'PC1000',
      profitCenterDescription: 'Treasury Finance',
      businessAreaDescription: 'Trade Structured Finance',
      portfolio: 'PF01',
      accountingCategory: 'AC01',
      iclGivenPrd: '26A',
      iclGivenPrdDesc: 'Inter-Co Loan Given',
      iclRecPrd: '26B',
      iclRecPrdDesc: 'Inter-Co Loan Received',
      targetReceivedCompanyCode: 'AE13',
      dms: {
        docType: 'D01',
        docTypeDesc: 'ICL Received Slip',
        docDate: '',
        filePath: '',
        fileName: '',
        dmsCode: '',
        uploaded: false,
        finalized: false,
      },
    },
    {
      statusCode: 'PENDING',
      client: '300',
      iclGivenCompanyCode: 'SG03',
      iclRequestNo: '22001830',
      requestDate: '12-08-26',
      startDate: '11-08-26',
      endDate: '06-08-27',
      plannedEndDate: '21-08-26',
      amount: 9345.79,
      currency: 'USD',
      dealId: '',
      iclReqStatus: '03',
      ottkNo: '101697',
      slcStructure: 'DSX',
      entityId: 'E021',
      entityString: 'E021 - OGA-DMCC-PAN',
      iclRecCompanyCode: '',
      depositRequest: '',
      houseBank: '',
      accountId: '',
      partnerBankId: '',
      enteredBy: 'ALOR',
      enteredOn: '12-08-26',
      entryTime: '11:403',
      requestedBy: 'OIL Treasury',
      requestorCoCode: 'SG03',
      requestorCoName: 'Olam Global Agri Pte. Ltd',
      requestorBank: 'SCB01',
      requestorBankName: 'Standard Chartered Singapore',
      expectedDate: '21-08-26',
      lcTenor: '12M',
      businessArea: 'TSF',
      ottkClassification: 'Direct',
      dttkNo: '',
      iclRequestStatusDescription: '03 - Approved for ICL Received',
      percentageRate: 5.25,
      fixing: 'Float',
      depositCompanyCode: '',
      depositTxn: '',
      wcdlCompanyCode: '',
      iclRecTxn: '',
      iclGivenTxn: '2601000533',
      companyName: 'Olam Global Agri Pte. Ltd',
      activeStatus: 'Active',
      productType: '26A',
      productTypeDescription: 'Inter-Co Loan Given',
      transactionType: '100',
      transactionTypeDescription: 'ICL Given',
      iclReceivedBank: '',
      activeActivity: 'Create',
      businessPartner: 'BP010333',
      profitCenter: 'PC1000',
      profitCenterDescription: 'Treasury Finance',
      businessAreaDescription: 'Trade Structured Finance',
      portfolio: 'PF01',
      accountingCategory: 'AC01',
      iclGivenPrd: '26A',
      iclGivenPrdDesc: 'Inter-Co Loan Given',
      iclRecPrd: '26B',
      iclRecPrdDesc: 'Inter-Co Loan Received',
      targetReceivedCompanyCode: 'AE13',
      dms: {
        docType: 'D01',
        docTypeDesc: 'ICL Received Slip',
        docDate: '',
        filePath: '',
        fileName: '',
        dmsCode: '',
        uploaded: false,
        finalized: false,
      },
    },
  ],
}
